set_property IOSTANDARD LVCMOS33 [get_ports {IO_B34_LN[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {IO_B34_LN[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {IO_B34_LN[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {IO_B34_LN[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {IO_B34_LN[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {IO_B34_LP[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {IO_B34_LP[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {IO_B34_LP[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {IO_B34_LP[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {IO_B34_LP[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {IO_B35_LP[24]}]
set_property IOSTANDARD LVCMOS33 [get_ports {IO_B35_LP[23]}]
set_property IOSTANDARD LVCMOS33 [get_ports {IO_B35_LP[22]}]
set_property IOSTANDARD LVCMOS33 [get_ports {IO_B35_LP[21]}]
set_property IOSTANDARD LVCMOS33 [get_ports {IO_B35_LP[20]}]
set_property IOSTANDARD LVCMOS33 [get_ports {IO_B35_LP[19]}]
set_property IOSTANDARD LVCMOS33 [get_ports {IO_B35_LP[18]}]
set_property IOSTANDARD LVCMOS33 [get_ports {IO_B35_LP[17]}]
set_property IOSTANDARD LVCMOS33 [get_ports {IO_B35_LP[16]}]
set_property IOSTANDARD LVCMOS33 [get_ports {IO_B35_LP[15]}]
set_property IOSTANDARD LVCMOS33 [get_ports {IO_B35_LP[14]}]
set_property IOSTANDARD LVCMOS33 [get_ports {IO_B35_LP[13]}]
set_property IOSTANDARD LVCMOS33 [get_ports {IO_B35_LP[12]}]
set_property IOSTANDARD LVCMOS33 [get_ports {IO_B35_LP[11]}]
set_property IOSTANDARD LVCMOS33 [get_ports {IO_B35_LP[10]}]
set_property IOSTANDARD LVCMOS33 [get_ports {IO_B35_LP[9]}]
set_property IOSTANDARD LVCMOS33 [get_ports {IO_B35_LP[8]}]
set_property IOSTANDARD LVCMOS33 [get_ports {IO_B35_LP[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {IO_B35_LP[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {IO_B35_LP[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {IO_B35_LP[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {IO_B35_LP[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {IO_B35_LP[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {IO_B35_LP[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {IO_B35_LN[24]}]
set_property IOSTANDARD LVCMOS33 [get_ports {IO_B35_LN[23]}]
set_property IOSTANDARD LVCMOS33 [get_ports {IO_B35_LN[22]}]
set_property IOSTANDARD LVCMOS33 [get_ports {IO_B35_LN[21]}]
set_property IOSTANDARD LVCMOS33 [get_ports {IO_B35_LN[20]}]
set_property IOSTANDARD LVCMOS33 [get_ports {IO_B35_LN[19]}]
set_property IOSTANDARD LVCMOS33 [get_ports {IO_B35_LN[18]}]
set_property IOSTANDARD LVCMOS33 [get_ports {IO_B35_LN[17]}]
set_property IOSTANDARD LVCMOS33 [get_ports {IO_B35_LN[16]}]
set_property IOSTANDARD LVCMOS33 [get_ports {IO_B35_LN[15]}]
set_property IOSTANDARD LVCMOS33 [get_ports {IO_B35_LN[14]}]
set_property IOSTANDARD LVCMOS33 [get_ports {IO_B35_LN[13]}]
set_property IOSTANDARD LVCMOS33 [get_ports {IO_B35_LN[12]}]
set_property IOSTANDARD LVCMOS33 [get_ports {IO_B35_LN[11]}]
set_property IOSTANDARD LVCMOS33 [get_ports {IO_B35_LN[10]}]
set_property IOSTANDARD LVCMOS33 [get_ports {IO_B35_LN[9]}]
set_property IOSTANDARD LVCMOS33 [get_ports {IO_B35_LN[8]}]
set_property IOSTANDARD LVCMOS33 [get_ports {IO_B35_LN[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {IO_B35_LN[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {IO_B35_LN[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {IO_B35_LN[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {IO_B35_LN[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {IO_B35_LN[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {IO_B35_LN[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LCD_DATA[15]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LCD_DATA[14]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LCD_DATA[13]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LCD_DATA[12]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LCD_DATA[11]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LCD_DATA[10]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LCD_DATA[9]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LCD_DATA[8]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LCD_DATA[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LCD_DATA[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LCD_DATA[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LCD_DATA[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LCD_DATA[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LCD_DATA[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LCD_DATA[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LCD_DATA[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LEDS[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LEDS[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LEDS[0]}]
set_property PACKAGE_PIN T11 [get_ports {IO_B34_LP[1]}]
set_property PACKAGE_PIN T10 [get_ports {IO_B34_LN[1]}]
set_property PACKAGE_PIN T12 [get_ports {IO_B34_LP[2]}]
set_property PACKAGE_PIN U12 [get_ports {IO_B34_LN[2]}]
set_property PACKAGE_PIN U13 [get_ports {IO_B34_LP[3]}]
set_property PACKAGE_PIN V13 [get_ports {IO_B34_LN[3]}]
set_property PACKAGE_PIN V12 [get_ports {IO_B34_LP[4]}]
set_property PACKAGE_PIN W13 [get_ports {IO_B34_LN[4]}]
set_property PACKAGE_PIN T14 [get_ports {IO_B34_LP[5]}]
set_property PACKAGE_PIN T15 [get_ports {IO_B34_LN[5]}]
set_property PACKAGE_PIN T16 [get_ports {LCD_DATA[0]}]
set_property PACKAGE_PIN U17 [get_ports {LCD_DATA[1]}]
set_property PACKAGE_PIN V15 [get_ports {LCD_DATA[2]}]
set_property PACKAGE_PIN W15 [get_ports {LCD_DATA[3]}]
set_property PACKAGE_PIN U18 [get_ports {LCD_DATA[4]}]
set_property PACKAGE_PIN U19 [get_ports {LCD_DATA[5]}]
set_property PACKAGE_PIN N18 [get_ports {LCD_DATA[6]}]
set_property PACKAGE_PIN P19 [get_ports {LCD_DATA[7]}]
set_property PACKAGE_PIN N20 [get_ports {LCD_DATA[8]}]
set_property PACKAGE_PIN P20 [get_ports {LCD_DATA[9]}]
set_property PACKAGE_PIN T20 [get_ports {LCD_DATA[10]}]
set_property PACKAGE_PIN U20 [get_ports {LCD_DATA[11]}]
set_property PACKAGE_PIN V20 [get_ports {LCD_DATA[12]}]
set_property PACKAGE_PIN W20 [get_ports {LCD_DATA[13]}]
set_property PACKAGE_PIN Y18 [get_ports {LCD_DATA[14]}]
set_property PACKAGE_PIN Y19 [get_ports {LCD_DATA[15]}]
set_property PACKAGE_PIN P18 [get_ports BP]
set_property PACKAGE_PIN P15 [get_ports I2C0_SDA]
set_property PACKAGE_PIN P16 [get_ports I2C0_SCL]
set_property IOSTANDARD LVCMOS33 [get_ports BP]
set_property IOSTANDARD LVCMOS33 [get_ports I2C0_SCL]
set_property IOSTANDARD LVCMOS33 [get_ports I2C0_SDA]
set_property PACKAGE_PIN N17 [get_ports MEMS_INTn]
set_property IOSTANDARD LVCMOS33 [get_ports MEMS_INTn]
set_property PACKAGE_PIN V16 [get_ports LCD_VSYNC]
set_property PACKAGE_PIN W16 [get_ports LCD_HSYNC]
set_property PACKAGE_PIN R16 [get_ports LCD_DE]
set_property PACKAGE_PIN R17 [get_ports LCD_PCLK]
set_property IOSTANDARD LVCMOS33 [get_ports LCD_PCLK]
set_property IOSTANDARD LVCMOS33 [get_ports LCD_HSYNC]
set_property IOSTANDARD LVCMOS33 [get_ports LCD_DE]
set_property IOSTANDARD LVCMOS33 [get_ports LCD_VSYNC]
set_property PACKAGE_PIN W18 [get_ports I2S_DIN]
set_property PACKAGE_PIN V18 [get_ports I2S_FSYNC_IN]
set_property IOSTANDARD LVCMOS33 [get_ports I2S_DIN]
set_property IOSTANDARD LVCMOS33 [get_ports I2S_FSYNC_IN]
set_property PACKAGE_PIN P14 [get_ports IO_B34_LP6]
set_property PACKAGE_PIN W14 [get_ports IO_B34_LP8]
set_property PACKAGE_PIN Y14 [get_ports IO_B34_LN8]
set_property PACKAGE_PIN U14 [get_ports IO_B34_LP11]
set_property PACKAGE_PIN U15 [get_ports IO_B34_LN11]
set_property IOSTANDARD LVCMOS33 [get_ports IO_B34_LP11]
set_property IOSTANDARD LVCMOS33 [get_ports IO_B34_LP8]
set_property IOSTANDARD LVCMOS33 [get_ports IO_B34_LN11]
set_property IOSTANDARD LVCMOS33 [get_ports IO_B34_LN8]
set_property IOSTANDARD LVCMOS33 [get_ports IO_B34_LP6]
set_property PACKAGE_PIN C20 [get_ports {IO_B35_LP[1]}]
set_property PACKAGE_PIN B20 [get_ports {IO_B35_LN[1]}]
set_property PACKAGE_PIN A20 [get_ports {IO_B35_LN[2]}]
set_property PACKAGE_PIN B19 [get_ports {IO_B35_LP[2]}]
set_property PACKAGE_PIN E17 [get_ports {IO_B35_LP[3]}]
set_property PACKAGE_PIN D18 [get_ports {IO_B35_LN[3]}]
set_property PACKAGE_PIN D19 [get_ports {IO_B35_LP[4]}]
set_property PACKAGE_PIN D20 [get_ports {IO_B35_LN[4]}]
set_property PACKAGE_PIN E18 [get_ports {IO_B35_LP[5]}]
set_property PACKAGE_PIN E19 [get_ports {IO_B35_LN[5]}]
set_property PACKAGE_PIN F16 [get_ports {IO_B35_LP[6]}]
set_property PACKAGE_PIN F17 [get_ports {IO_B35_LN[6]}]
set_property PACKAGE_PIN M19 [get_ports {IO_B35_LP[7]}]
set_property PACKAGE_PIN M20 [get_ports {IO_B35_LN[7]}]
set_property PACKAGE_PIN M17 [get_ports {IO_B35_LP[8]}]
set_property PACKAGE_PIN M18 [get_ports {IO_B35_LN[8]}]
set_property PACKAGE_PIN L19 [get_ports {IO_B35_LP[9]}]
set_property PACKAGE_PIN L20 [get_ports {IO_B35_LN[9]}]
set_property PACKAGE_PIN K19 [get_ports {IO_B35_LP[10]}]
set_property PACKAGE_PIN J19 [get_ports {IO_B35_LN[10]}]
set_property PACKAGE_PIN L16 [get_ports {IO_B35_LP[11]}]
set_property PACKAGE_PIN L17 [get_ports {IO_B35_LN[11]}]
set_property PACKAGE_PIN K17 [get_ports {IO_B35_LP[12]}]
set_property PACKAGE_PIN K18 [get_ports {IO_B35_LN[12]}]
set_property PACKAGE_PIN H16 [get_ports {IO_B35_LP[13]}]
set_property PACKAGE_PIN H17 [get_ports {IO_B35_LN[13]}]
set_property PACKAGE_PIN J18 [get_ports {IO_B35_LP[14]}]
set_property PACKAGE_PIN H18 [get_ports {IO_B35_LN[14]}]
set_property PACKAGE_PIN F19 [get_ports {IO_B35_LP[15]}]
set_property PACKAGE_PIN F20 [get_ports {IO_B35_LN[15]}]
set_property PACKAGE_PIN G17 [get_ports {IO_B35_LP[16]}]
set_property PACKAGE_PIN G18 [get_ports {IO_B35_LN[16]}]
set_property PACKAGE_PIN J20 [get_ports {IO_B35_LP[17]}]
set_property PACKAGE_PIN H20 [get_ports {IO_B35_LN[17]}]
set_property PACKAGE_PIN G19 [get_ports {IO_B35_LP[18]}]
set_property PACKAGE_PIN G20 [get_ports {IO_B35_LN[18]}]
set_property PACKAGE_PIN H15 [get_ports {IO_B35_LP[19]}]
set_property PACKAGE_PIN G15 [get_ports {IO_B35_LN[19]}]
set_property PACKAGE_PIN K14 [get_ports {IO_B35_LP[20]}]
set_property PACKAGE_PIN J14 [get_ports {IO_B35_LN[20]}]
set_property PACKAGE_PIN N15 [get_ports {IO_B35_LP[21]}]
set_property PACKAGE_PIN N16 [get_ports {IO_B35_LN[21]}]
set_property PACKAGE_PIN L14 [get_ports {IO_B35_LP[22]}]
set_property PACKAGE_PIN L15 [get_ports {IO_B35_LN[22]}]
set_property PACKAGE_PIN M14 [get_ports {IO_B35_LP[23]}]
set_property PACKAGE_PIN M15 [get_ports {IO_B35_LN[23]}]
set_property PACKAGE_PIN K16 [get_ports {IO_B35_LP[24]}]
set_property PACKAGE_PIN J16 [get_ports {IO_B35_LN[24]}]
set_property IOSTANDARD LVCMOS33 [get_ports {SW[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {SW[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {SW[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {SW[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports HDMI_INTn]
set_property PACKAGE_PIN W19 [get_ports HDMI_INTn]
set_property IOSTANDARD LVCMOS33 [get_ports I2S_FSYNC_OUT]
set_property IOSTANDARD LVCMOS33 [get_ports I2S_SCLK]
set_property IOSTANDARD LVCMOS33 [get_ports I2S_DOUT]
set_property PACKAGE_PIN V17 [get_ports I2S_DOUT]
set_property PACKAGE_PIN T17 [get_ports I2S_SCLK]
set_property PACKAGE_PIN R18 [get_ports I2S_FSYNC_OUT]
set_property PACKAGE_PIN R19 [get_ports {SW[0]}]
set_property PACKAGE_PIN T19 [get_ports {SW[1]}]
set_property PACKAGE_PIN G14 [get_ports {SW[2]}]
set_property PACKAGE_PIN J15 [get_ports {SW[3]}]
#set_property PACKAGE_PIN Y16 [get_ports {LEDS[0]}]
#set_property PACKAGE_PIN Y17 [get_ports {LEDS[1]}]
set_property PACKAGE_PIN R14 [get_ports {LEDS[2]}]

set_property PACKAGE_PIN Y9 [get_ports ADC_CK]
set_property PACKAGE_PIN Y6 [get_ports {AD[11]}]
set_property PACKAGE_PIN V8 [get_ports {AD[10]}]
set_property PACKAGE_PIN V10 [get_ports {AD[9]}]
set_property PACKAGE_PIN T11 [get_ports {AD[8]}]
set_property PACKAGE_PIN W8 [get_ports {AD[7]}]
set_property PACKAGE_PIN T10 [get_ports {AD[6]}]
set_property PACKAGE_PIN T12 [get_ports {AD[5]}]
set_property PACKAGE_PIN U13 [get_ports {AD[4]}]
set_property PACKAGE_PIN U12 [get_ports {AD[3]}]
set_property PACKAGE_PIN V13 [get_ports {AD[2]}]
set_property PACKAGE_PIN V12 [get_ports {AD[1]}]
set_property PACKAGE_PIN W13 [get_ports {AD[0]}]
set_property PACKAGE_PIN V11 [get_ports OFA]
set_property PACKAGE_PIN U10 [get_ports MUX]
set_property PACKAGE_PIN Y16 [get_ports SHDNA]
set_property PACKAGE_PIN Y17 [get_ports SHDNB]
set_property IOSTANDARD LVCMOS33 [get_ports ADC_CK]
set_property IOSTANDARD LVCMOS33 [get_ports {AD[*]}]
set_property IOSTANDARD LVCMOS33 [get_ports SHDNA]
set_property IOSTANDARD LVCMOS33 [get_ports SHDNB]
set_property IOSTANDARD LVCMOS33 [get_ports MUX]
set_property IOSTANDARD LVCMOS33 [get_ports OFA]

create_clock -period 25.000 -name adck [get_ports ADC_CK]

set_property CFGBVS VCCO [current_design]
set_property CONFIG_VOLTAGE 3.3 [current_design]




create_debug_core u_ila_0 ila
set_property ALL_PROBE_SAME_MU true [get_debug_cores u_ila_0]
set_property ALL_PROBE_SAME_MU_CNT 1 [get_debug_cores u_ila_0]
set_property C_ADV_TRIGGER false [get_debug_cores u_ila_0]
set_property C_DATA_DEPTH 1024 [get_debug_cores u_ila_0]
set_property C_EN_STRG_QUAL false [get_debug_cores u_ila_0]
set_property C_INPUT_PIPE_STAGES 0 [get_debug_cores u_ila_0]
set_property C_TRIGIN_EN false [get_debug_cores u_ila_0]
set_property C_TRIGOUT_EN false [get_debug_cores u_ila_0]
set_property port_width 1 [get_debug_ports u_ila_0/clk]
connect_debug_port u_ila_0/clk [get_nets [list w_adck]]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe0]
set_property port_width 14 [get_debug_ports u_ila_0/probe0]
connect_debug_port u_ila_0/probe0 [get_nets [list {w_q[0]} {w_q[1]} {w_q[2]} {w_q[3]} {w_q[4]} {w_q[5]} {w_q[6]} {w_q[7]} {w_q[8]} {w_q[9]} {w_q[10]} {w_q[11]} {w_q[12]} {w_q[13]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe1]
set_property port_width 12 [get_debug_ports u_ila_0/probe1]
connect_debug_port u_ila_0/probe1 [get_nets [list {w_ad[0]} {w_ad[1]} {w_ad[2]} {w_ad[3]} {w_ad[4]} {w_ad[5]} {w_ad[6]} {w_ad[7]} {w_ad[8]} {w_ad[9]} {w_ad[10]} {w_ad[11]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe2]
set_property port_width 14 [get_debug_ports u_ila_0/probe2]
connect_debug_port u_ila_0/probe2 [get_nets [list {w_i[0]} {w_i[1]} {w_i[2]} {w_i[3]} {w_i[4]} {w_i[5]} {w_i[6]} {w_i[7]} {w_i[8]} {w_i[9]} {w_i[10]} {w_i[11]} {w_i[12]} {w_i[13]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe3]
set_property port_width 32 [get_debug_ports u_ila_0/probe3]
connect_debug_port u_ila_0/probe3 [get_nets [list {w_bram_dout[0]} {w_bram_dout[1]} {w_bram_dout[2]} {w_bram_dout[3]} {w_bram_dout[4]} {w_bram_dout[5]} {w_bram_dout[6]} {w_bram_dout[7]} {w_bram_dout[8]} {w_bram_dout[9]} {w_bram_dout[10]} {w_bram_dout[11]} {w_bram_dout[12]} {w_bram_dout[13]} {w_bram_dout[14]} {w_bram_dout[15]} {w_bram_dout[16]} {w_bram_dout[17]} {w_bram_dout[18]} {w_bram_dout[19]} {w_bram_dout[20]} {w_bram_dout[21]} {w_bram_dout[22]} {w_bram_dout[23]} {w_bram_dout[24]} {w_bram_dout[25]} {w_bram_dout[26]} {w_bram_dout[27]} {w_bram_dout[28]} {w_bram_dout[29]} {w_bram_dout[30]} {w_bram_dout[31]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe4]
set_property port_width 29 [get_debug_ports u_ila_0/probe4]
connect_debug_port u_ila_0/probe4 [get_nets [list {cic_q/r_tmp[0]} {cic_q/r_tmp[1]} {cic_q/r_tmp[2]} {cic_q/r_tmp[3]} {cic_q/r_tmp[4]} {cic_q/r_tmp[5]} {cic_q/r_tmp[6]} {cic_q/r_tmp[7]} {cic_q/r_tmp[8]} {cic_q/r_tmp[9]} {cic_q/r_tmp[10]} {cic_q/r_tmp[11]} {cic_q/r_tmp[12]} {cic_q/r_tmp[13]} {cic_q/r_tmp[14]} {cic_q/r_tmp[15]} {cic_q/r_tmp[16]} {cic_q/r_tmp[17]} {cic_q/r_tmp[18]} {cic_q/r_tmp[19]} {cic_q/r_tmp[20]} {cic_q/r_tmp[21]} {cic_q/r_tmp[22]} {cic_q/r_tmp[23]} {cic_q/r_tmp[24]} {cic_q/r_tmp[25]} {cic_q/r_tmp[26]} {cic_q/r_tmp[27]} {cic_q/r_tmp[28]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe5]
set_property port_width 29 [get_debug_ports u_ila_0/probe5]
connect_debug_port u_ila_0/probe5 [get_nets [list {cic_i/r_sum3[0]} {cic_i/r_sum3[1]} {cic_i/r_sum3[2]} {cic_i/r_sum3[3]} {cic_i/r_sum3[4]} {cic_i/r_sum3[5]} {cic_i/r_sum3[6]} {cic_i/r_sum3[7]} {cic_i/r_sum3[8]} {cic_i/r_sum3[9]} {cic_i/r_sum3[10]} {cic_i/r_sum3[11]} {cic_i/r_sum3[12]} {cic_i/r_sum3[13]} {cic_i/r_sum3[14]} {cic_i/r_sum3[15]} {cic_i/r_sum3[16]} {cic_i/r_sum3[17]} {cic_i/r_sum3[18]} {cic_i/r_sum3[19]} {cic_i/r_sum3[20]} {cic_i/r_sum3[21]} {cic_i/r_sum3[22]} {cic_i/r_sum3[23]} {cic_i/r_sum3[24]} {cic_i/r_sum3[25]} {cic_i/r_sum3[26]} {cic_i/r_sum3[27]} {cic_i/r_sum3[28]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe6]
set_property port_width 8 [get_debug_ports u_ila_0/probe6]
connect_debug_port u_ila_0/probe6 [get_nets [list {cic_q/r_cnt_reg[0]} {cic_q/r_cnt_reg[1]} {cic_q/r_cnt_reg[2]} {cic_q/r_cnt_reg[3]} {cic_q/r_cnt_reg[4]} {cic_q/r_cnt_reg[5]} {cic_q/r_cnt_reg[6]} {cic_q/r_cnt_reg[7]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe7]
set_property port_width 29 [get_debug_ports u_ila_0/probe7]
connect_debug_port u_ila_0/probe7 [get_nets [list {cic_i/r_dif1[0]} {cic_i/r_dif1[1]} {cic_i/r_dif1[2]} {cic_i/r_dif1[3]} {cic_i/r_dif1[4]} {cic_i/r_dif1[5]} {cic_i/r_dif1[6]} {cic_i/r_dif1[7]} {cic_i/r_dif1[8]} {cic_i/r_dif1[9]} {cic_i/r_dif1[10]} {cic_i/r_dif1[11]} {cic_i/r_dif1[12]} {cic_i/r_dif1[13]} {cic_i/r_dif1[14]} {cic_i/r_dif1[15]} {cic_i/r_dif1[16]} {cic_i/r_dif1[17]} {cic_i/r_dif1[18]} {cic_i/r_dif1[19]} {cic_i/r_dif1[20]} {cic_i/r_dif1[21]} {cic_i/r_dif1[22]} {cic_i/r_dif1[23]} {cic_i/r_dif1[24]} {cic_i/r_dif1[25]} {cic_i/r_dif1[26]} {cic_i/r_dif1[27]} {cic_i/r_dif1[28]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe8]
set_property port_width 29 [get_debug_ports u_ila_0/probe8]
connect_debug_port u_ila_0/probe8 [get_nets [list {cic_q/r_dif3[0]} {cic_q/r_dif3[1]} {cic_q/r_dif3[2]} {cic_q/r_dif3[3]} {cic_q/r_dif3[4]} {cic_q/r_dif3[5]} {cic_q/r_dif3[6]} {cic_q/r_dif3[7]} {cic_q/r_dif3[8]} {cic_q/r_dif3[9]} {cic_q/r_dif3[10]} {cic_q/r_dif3[11]} {cic_q/r_dif3[12]} {cic_q/r_dif3[13]} {cic_q/r_dif3[14]} {cic_q/r_dif3[15]} {cic_q/r_dif3[16]} {cic_q/r_dif3[17]} {cic_q/r_dif3[18]} {cic_q/r_dif3[19]} {cic_q/r_dif3[20]} {cic_q/r_dif3[21]} {cic_q/r_dif3[22]} {cic_q/r_dif3[23]} {cic_q/r_dif3[24]} {cic_q/r_dif3[25]} {cic_q/r_dif3[26]} {cic_q/r_dif3[27]} {cic_q/r_dif3[28]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe9]
set_property port_width 29 [get_debug_ports u_ila_0/probe9]
connect_debug_port u_ila_0/probe9 [get_nets [list {cic_q/r_sum3[0]} {cic_q/r_sum3[1]} {cic_q/r_sum3[2]} {cic_q/r_sum3[3]} {cic_q/r_sum3[4]} {cic_q/r_sum3[5]} {cic_q/r_sum3[6]} {cic_q/r_sum3[7]} {cic_q/r_sum3[8]} {cic_q/r_sum3[9]} {cic_q/r_sum3[10]} {cic_q/r_sum3[11]} {cic_q/r_sum3[12]} {cic_q/r_sum3[13]} {cic_q/r_sum3[14]} {cic_q/r_sum3[15]} {cic_q/r_sum3[16]} {cic_q/r_sum3[17]} {cic_q/r_sum3[18]} {cic_q/r_sum3[19]} {cic_q/r_sum3[20]} {cic_q/r_sum3[21]} {cic_q/r_sum3[22]} {cic_q/r_sum3[23]} {cic_q/r_sum3[24]} {cic_q/r_sum3[25]} {cic_q/r_sum3[26]} {cic_q/r_sum3[27]} {cic_q/r_sum3[28]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe10]
set_property port_width 8 [get_debug_ports u_ila_0/probe10]
connect_debug_port u_ila_0/probe10 [get_nets [list {cic_i/r_cnt_reg__0[0]} {cic_i/r_cnt_reg__0[1]} {cic_i/r_cnt_reg__0[2]} {cic_i/r_cnt_reg__0[3]} {cic_i/r_cnt_reg__0[4]} {cic_i/r_cnt_reg__0[5]} {cic_i/r_cnt_reg__0[6]} {cic_i/r_cnt_reg__0[7]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe11]
set_property port_width 29 [get_debug_ports u_ila_0/probe11]
connect_debug_port u_ila_0/probe11 [get_nets [list {cic_i/r_out0[0]} {cic_i/r_out0[1]} {cic_i/r_out0[2]} {cic_i/r_out0[3]} {cic_i/r_out0[4]} {cic_i/r_out0[5]} {cic_i/r_out0[6]} {cic_i/r_out0[7]} {cic_i/r_out0[8]} {cic_i/r_out0[9]} {cic_i/r_out0[10]} {cic_i/r_out0[11]} {cic_i/r_out0[12]} {cic_i/r_out0[13]} {cic_i/r_out0[14]} {cic_i/r_out0[15]} {cic_i/r_out0[16]} {cic_i/r_out0[17]} {cic_i/r_out0[18]} {cic_i/r_out0[19]} {cic_i/r_out0[20]} {cic_i/r_out0[21]} {cic_i/r_out0[22]} {cic_i/r_out0[23]} {cic_i/r_out0[24]} {cic_i/r_out0[25]} {cic_i/r_out0[26]} {cic_i/r_out0[27]} {cic_i/r_out0[28]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe12]
set_property port_width 29 [get_debug_ports u_ila_0/probe12]
connect_debug_port u_ila_0/probe12 [get_nets [list {cic_i/r_dif3[0]} {cic_i/r_dif3[1]} {cic_i/r_dif3[2]} {cic_i/r_dif3[3]} {cic_i/r_dif3[4]} {cic_i/r_dif3[5]} {cic_i/r_dif3[6]} {cic_i/r_dif3[7]} {cic_i/r_dif3[8]} {cic_i/r_dif3[9]} {cic_i/r_dif3[10]} {cic_i/r_dif3[11]} {cic_i/r_dif3[12]} {cic_i/r_dif3[13]} {cic_i/r_dif3[14]} {cic_i/r_dif3[15]} {cic_i/r_dif3[16]} {cic_i/r_dif3[17]} {cic_i/r_dif3[18]} {cic_i/r_dif3[19]} {cic_i/r_dif3[20]} {cic_i/r_dif3[21]} {cic_i/r_dif3[22]} {cic_i/r_dif3[23]} {cic_i/r_dif3[24]} {cic_i/r_dif3[25]} {cic_i/r_dif3[26]} {cic_i/r_dif3[27]} {cic_i/r_dif3[28]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe13]
set_property port_width 29 [get_debug_ports u_ila_0/probe13]
connect_debug_port u_ila_0/probe13 [get_nets [list {cic_i/r_tmp[0]} {cic_i/r_tmp[1]} {cic_i/r_tmp[2]} {cic_i/r_tmp[3]} {cic_i/r_tmp[4]} {cic_i/r_tmp[5]} {cic_i/r_tmp[6]} {cic_i/r_tmp[7]} {cic_i/r_tmp[8]} {cic_i/r_tmp[9]} {cic_i/r_tmp[10]} {cic_i/r_tmp[11]} {cic_i/r_tmp[12]} {cic_i/r_tmp[13]} {cic_i/r_tmp[14]} {cic_i/r_tmp[15]} {cic_i/r_tmp[16]} {cic_i/r_tmp[17]} {cic_i/r_tmp[18]} {cic_i/r_tmp[19]} {cic_i/r_tmp[20]} {cic_i/r_tmp[21]} {cic_i/r_tmp[22]} {cic_i/r_tmp[23]} {cic_i/r_tmp[24]} {cic_i/r_tmp[25]} {cic_i/r_tmp[26]} {cic_i/r_tmp[27]} {cic_i/r_tmp[28]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe14]
set_property port_width 29 [get_debug_ports u_ila_0/probe14]
connect_debug_port u_ila_0/probe14 [get_nets [list {cic_i/r_dif2[0]} {cic_i/r_dif2[1]} {cic_i/r_dif2[2]} {cic_i/r_dif2[3]} {cic_i/r_dif2[4]} {cic_i/r_dif2[5]} {cic_i/r_dif2[6]} {cic_i/r_dif2[7]} {cic_i/r_dif2[8]} {cic_i/r_dif2[9]} {cic_i/r_dif2[10]} {cic_i/r_dif2[11]} {cic_i/r_dif2[12]} {cic_i/r_dif2[13]} {cic_i/r_dif2[14]} {cic_i/r_dif2[15]} {cic_i/r_dif2[16]} {cic_i/r_dif2[17]} {cic_i/r_dif2[18]} {cic_i/r_dif2[19]} {cic_i/r_dif2[20]} {cic_i/r_dif2[21]} {cic_i/r_dif2[22]} {cic_i/r_dif2[23]} {cic_i/r_dif2[24]} {cic_i/r_dif2[25]} {cic_i/r_dif2[26]} {cic_i/r_dif2[27]} {cic_i/r_dif2[28]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe15]
set_property port_width 29 [get_debug_ports u_ila_0/probe15]
connect_debug_port u_ila_0/probe15 [get_nets [list {cic_i/r_sum2[0]} {cic_i/r_sum2[1]} {cic_i/r_sum2[2]} {cic_i/r_sum2[3]} {cic_i/r_sum2[4]} {cic_i/r_sum2[5]} {cic_i/r_sum2[6]} {cic_i/r_sum2[7]} {cic_i/r_sum2[8]} {cic_i/r_sum2[9]} {cic_i/r_sum2[10]} {cic_i/r_sum2[11]} {cic_i/r_sum2[12]} {cic_i/r_sum2[13]} {cic_i/r_sum2[14]} {cic_i/r_sum2[15]} {cic_i/r_sum2[16]} {cic_i/r_sum2[17]} {cic_i/r_sum2[18]} {cic_i/r_sum2[19]} {cic_i/r_sum2[20]} {cic_i/r_sum2[21]} {cic_i/r_sum2[22]} {cic_i/r_sum2[23]} {cic_i/r_sum2[24]} {cic_i/r_sum2[25]} {cic_i/r_sum2[26]} {cic_i/r_sum2[27]} {cic_i/r_sum2[28]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe16]
set_property port_width 29 [get_debug_ports u_ila_0/probe16]
connect_debug_port u_ila_0/probe16 [get_nets [list {cic_q/r_dif1[0]} {cic_q/r_dif1[1]} {cic_q/r_dif1[2]} {cic_q/r_dif1[3]} {cic_q/r_dif1[4]} {cic_q/r_dif1[5]} {cic_q/r_dif1[6]} {cic_q/r_dif1[7]} {cic_q/r_dif1[8]} {cic_q/r_dif1[9]} {cic_q/r_dif1[10]} {cic_q/r_dif1[11]} {cic_q/r_dif1[12]} {cic_q/r_dif1[13]} {cic_q/r_dif1[14]} {cic_q/r_dif1[15]} {cic_q/r_dif1[16]} {cic_q/r_dif1[17]} {cic_q/r_dif1[18]} {cic_q/r_dif1[19]} {cic_q/r_dif1[20]} {cic_q/r_dif1[21]} {cic_q/r_dif1[22]} {cic_q/r_dif1[23]} {cic_q/r_dif1[24]} {cic_q/r_dif1[25]} {cic_q/r_dif1[26]} {cic_q/r_dif1[27]} {cic_q/r_dif1[28]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe17]
set_property port_width 29 [get_debug_ports u_ila_0/probe17]
connect_debug_port u_ila_0/probe17 [get_nets [list {cic_q/r_out0[0]} {cic_q/r_out0[1]} {cic_q/r_out0[2]} {cic_q/r_out0[3]} {cic_q/r_out0[4]} {cic_q/r_out0[5]} {cic_q/r_out0[6]} {cic_q/r_out0[7]} {cic_q/r_out0[8]} {cic_q/r_out0[9]} {cic_q/r_out0[10]} {cic_q/r_out0[11]} {cic_q/r_out0[12]} {cic_q/r_out0[13]} {cic_q/r_out0[14]} {cic_q/r_out0[15]} {cic_q/r_out0[16]} {cic_q/r_out0[17]} {cic_q/r_out0[18]} {cic_q/r_out0[19]} {cic_q/r_out0[20]} {cic_q/r_out0[21]} {cic_q/r_out0[22]} {cic_q/r_out0[23]} {cic_q/r_out0[24]} {cic_q/r_out0[25]} {cic_q/r_out0[26]} {cic_q/r_out0[27]} {cic_q/r_out0[28]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe18]
set_property port_width 29 [get_debug_ports u_ila_0/probe18]
connect_debug_port u_ila_0/probe18 [get_nets [list {cic_q/r_sum2[0]} {cic_q/r_sum2[1]} {cic_q/r_sum2[2]} {cic_q/r_sum2[3]} {cic_q/r_sum2[4]} {cic_q/r_sum2[5]} {cic_q/r_sum2[6]} {cic_q/r_sum2[7]} {cic_q/r_sum2[8]} {cic_q/r_sum2[9]} {cic_q/r_sum2[10]} {cic_q/r_sum2[11]} {cic_q/r_sum2[12]} {cic_q/r_sum2[13]} {cic_q/r_sum2[14]} {cic_q/r_sum2[15]} {cic_q/r_sum2[16]} {cic_q/r_sum2[17]} {cic_q/r_sum2[18]} {cic_q/r_sum2[19]} {cic_q/r_sum2[20]} {cic_q/r_sum2[21]} {cic_q/r_sum2[22]} {cic_q/r_sum2[23]} {cic_q/r_sum2[24]} {cic_q/r_sum2[25]} {cic_q/r_sum2[26]} {cic_q/r_sum2[27]} {cic_q/r_sum2[28]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe19]
set_property port_width 29 [get_debug_ports u_ila_0/probe19]
connect_debug_port u_ila_0/probe19 [get_nets [list {cic_q/r_dif2[0]} {cic_q/r_dif2[1]} {cic_q/r_dif2[2]} {cic_q/r_dif2[3]} {cic_q/r_dif2[4]} {cic_q/r_dif2[5]} {cic_q/r_dif2[6]} {cic_q/r_dif2[7]} {cic_q/r_dif2[8]} {cic_q/r_dif2[9]} {cic_q/r_dif2[10]} {cic_q/r_dif2[11]} {cic_q/r_dif2[12]} {cic_q/r_dif2[13]} {cic_q/r_dif2[14]} {cic_q/r_dif2[15]} {cic_q/r_dif2[16]} {cic_q/r_dif2[17]} {cic_q/r_dif2[18]} {cic_q/r_dif2[19]} {cic_q/r_dif2[20]} {cic_q/r_dif2[21]} {cic_q/r_dif2[22]} {cic_q/r_dif2[23]} {cic_q/r_dif2[24]} {cic_q/r_dif2[25]} {cic_q/r_dif2[26]} {cic_q/r_dif2[27]} {cic_q/r_dif2[28]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe20]
set_property port_width 1 [get_debug_ports u_ila_0/probe20]
connect_debug_port u_ila_0/probe20 [get_nets [list r_axis_tvalid]]
set_property C_CLK_INPUT_FREQ_HZ 300000000 [get_debug_cores dbg_hub]
set_property C_ENABLE_CLK_DIVIDER false [get_debug_cores dbg_hub]
set_property C_USER_SCAN_CHAIN 1 [get_debug_cores dbg_hub]
connect_debug_port dbg_hub/clk [get_nets w_adck]
