set_property IOSTANDARD LVCMOS33 [get_ports {IO_B34_LN[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {IO_B34_LN[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {IO_B34_LN[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {IO_B34_LN[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {IO_B34_LN[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {IO_B34_LP[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {IO_B34_LP[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {IO_B34_LP[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {IO_B34_LP[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {IO_B34_LP[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {IO_B35_LP[24]}]
set_property IOSTANDARD LVCMOS33 [get_ports {IO_B35_LP[23]}]
set_property IOSTANDARD LVCMOS33 [get_ports {IO_B35_LP[22]}]
set_property IOSTANDARD LVCMOS33 [get_ports {IO_B35_LP[21]}]
set_property IOSTANDARD LVCMOS33 [get_ports {IO_B35_LP[20]}]
set_property IOSTANDARD LVCMOS33 [get_ports {IO_B35_LP[19]}]
set_property IOSTANDARD LVCMOS33 [get_ports {IO_B35_LP[18]}]
set_property IOSTANDARD LVCMOS33 [get_ports {IO_B35_LP[17]}]
set_property IOSTANDARD LVCMOS33 [get_ports {IO_B35_LP[16]}]
set_property IOSTANDARD LVCMOS33 [get_ports {IO_B35_LP[15]}]
set_property IOSTANDARD LVCMOS33 [get_ports {IO_B35_LP[14]}]
set_property IOSTANDARD LVCMOS33 [get_ports {IO_B35_LP[13]}]
set_property IOSTANDARD LVCMOS33 [get_ports {IO_B35_LP[12]}]
set_property IOSTANDARD LVCMOS33 [get_ports {IO_B35_LP[11]}]
set_property IOSTANDARD LVCMOS33 [get_ports {IO_B35_LP[10]}]
set_property IOSTANDARD LVCMOS33 [get_ports {IO_B35_LP[9]}]
set_property IOSTANDARD LVCMOS33 [get_ports {IO_B35_LP[8]}]
set_property IOSTANDARD LVCMOS33 [get_ports {IO_B35_LP[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {IO_B35_LP[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {IO_B35_LP[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {IO_B35_LP[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {IO_B35_LP[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {IO_B35_LP[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {IO_B35_LP[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {IO_B35_LN[24]}]
set_property IOSTANDARD LVCMOS33 [get_ports {IO_B35_LN[23]}]
set_property IOSTANDARD LVCMOS33 [get_ports {IO_B35_LN[22]}]
set_property IOSTANDARD LVCMOS33 [get_ports {IO_B35_LN[21]}]
set_property IOSTANDARD LVCMOS33 [get_ports {IO_B35_LN[20]}]
set_property IOSTANDARD LVCMOS33 [get_ports {IO_B35_LN[19]}]
set_property IOSTANDARD LVCMOS33 [get_ports {IO_B35_LN[18]}]
set_property IOSTANDARD LVCMOS33 [get_ports {IO_B35_LN[17]}]
set_property IOSTANDARD LVCMOS33 [get_ports {IO_B35_LN[16]}]
set_property IOSTANDARD LVCMOS33 [get_ports {IO_B35_LN[15]}]
set_property IOSTANDARD LVCMOS33 [get_ports {IO_B35_LN[14]}]
set_property IOSTANDARD LVCMOS33 [get_ports {IO_B35_LN[13]}]
set_property IOSTANDARD LVCMOS33 [get_ports {IO_B35_LN[12]}]
set_property IOSTANDARD LVCMOS33 [get_ports {IO_B35_LN[11]}]
set_property IOSTANDARD LVCMOS33 [get_ports {IO_B35_LN[10]}]
set_property IOSTANDARD LVCMOS33 [get_ports {IO_B35_LN[9]}]
set_property IOSTANDARD LVCMOS33 [get_ports {IO_B35_LN[8]}]
set_property IOSTANDARD LVCMOS33 [get_ports {IO_B35_LN[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {IO_B35_LN[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {IO_B35_LN[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {IO_B35_LN[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {IO_B35_LN[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {IO_B35_LN[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {IO_B35_LN[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LCD_DATA[15]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LCD_DATA[14]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LCD_DATA[13]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LCD_DATA[12]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LCD_DATA[11]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LCD_DATA[10]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LCD_DATA[9]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LCD_DATA[8]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LCD_DATA[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LCD_DATA[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LCD_DATA[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LCD_DATA[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LCD_DATA[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LCD_DATA[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LCD_DATA[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LCD_DATA[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LEDS[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LEDS[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LEDS[0]}]
set_property PACKAGE_PIN T11 [get_ports {IO_B34_LP[1]}]
set_property PACKAGE_PIN T10 [get_ports {IO_B34_LN[1]}]
set_property PACKAGE_PIN T12 [get_ports {IO_B34_LP[2]}]
set_property PACKAGE_PIN U12 [get_ports {IO_B34_LN[2]}]
set_property PACKAGE_PIN U13 [get_ports {IO_B34_LP[3]}]
set_property PACKAGE_PIN V13 [get_ports {IO_B34_LN[3]}]
set_property PACKAGE_PIN V12 [get_ports {IO_B34_LP[4]}]
set_property PACKAGE_PIN W13 [get_ports {IO_B34_LN[4]}]
set_property PACKAGE_PIN T14 [get_ports {IO_B34_LP[5]}]
set_property PACKAGE_PIN T15 [get_ports {IO_B34_LN[5]}]
set_property PACKAGE_PIN T16 [get_ports {LCD_DATA[0]}]
set_property PACKAGE_PIN U17 [get_ports {LCD_DATA[1]}]
set_property PACKAGE_PIN V15 [get_ports {LCD_DATA[2]}]
set_property PACKAGE_PIN W15 [get_ports {LCD_DATA[3]}]
set_property PACKAGE_PIN U18 [get_ports {LCD_DATA[4]}]
set_property PACKAGE_PIN U19 [get_ports {LCD_DATA[5]}]
set_property PACKAGE_PIN N18 [get_ports {LCD_DATA[6]}]
set_property PACKAGE_PIN P19 [get_ports {LCD_DATA[7]}]
set_property PACKAGE_PIN N20 [get_ports {LCD_DATA[8]}]
set_property PACKAGE_PIN P20 [get_ports {LCD_DATA[9]}]
set_property PACKAGE_PIN T20 [get_ports {LCD_DATA[10]}]
set_property PACKAGE_PIN U20 [get_ports {LCD_DATA[11]}]
set_property PACKAGE_PIN V20 [get_ports {LCD_DATA[12]}]
set_property PACKAGE_PIN W20 [get_ports {LCD_DATA[13]}]
set_property PACKAGE_PIN Y18 [get_ports {LCD_DATA[14]}]
set_property PACKAGE_PIN Y19 [get_ports {LCD_DATA[15]}]
set_property PACKAGE_PIN P18 [get_ports BP]
set_property PACKAGE_PIN P15 [get_ports I2C0_SDA]
set_property PACKAGE_PIN P16 [get_ports I2C0_SCL]
set_property IOSTANDARD LVCMOS33 [get_ports BP]
set_property IOSTANDARD LVCMOS33 [get_ports I2C0_SCL]
set_property IOSTANDARD LVCMOS33 [get_ports I2C0_SDA]
set_property PACKAGE_PIN N17 [get_ports MEMS_INTn]
set_property IOSTANDARD LVCMOS33 [get_ports MEMS_INTn]
set_property PACKAGE_PIN V16 [get_ports LCD_VSYNC]
set_property PACKAGE_PIN W16 [get_ports LCD_HSYNC]
set_property PACKAGE_PIN R16 [get_ports LCD_DE]
set_property PACKAGE_PIN R17 [get_ports LCD_PCLK]
set_property IOSTANDARD LVCMOS33 [get_ports LCD_PCLK]
set_property IOSTANDARD LVCMOS33 [get_ports LCD_HSYNC]
set_property IOSTANDARD LVCMOS33 [get_ports LCD_DE]
set_property IOSTANDARD LVCMOS33 [get_ports LCD_VSYNC]
set_property PACKAGE_PIN W18 [get_ports I2S_DIN]
set_property PACKAGE_PIN V18 [get_ports I2S_FSYNC_IN]
set_property IOSTANDARD LVCMOS33 [get_ports I2S_DIN]
set_property IOSTANDARD LVCMOS33 [get_ports I2S_FSYNC_IN]
set_property PACKAGE_PIN P14 [get_ports IO_B34_LP6]
set_property PACKAGE_PIN W14 [get_ports IO_B34_LP8]
set_property PACKAGE_PIN Y14 [get_ports IO_B34_LN8]
set_property PACKAGE_PIN U14 [get_ports IO_B34_LP11]
set_property PACKAGE_PIN U15 [get_ports IO_B34_LN11]
set_property IOSTANDARD LVCMOS33 [get_ports IO_B34_LP11]
set_property IOSTANDARD LVCMOS33 [get_ports IO_B34_LP8]
set_property IOSTANDARD LVCMOS33 [get_ports IO_B34_LN11]
set_property IOSTANDARD LVCMOS33 [get_ports IO_B34_LN8]
set_property IOSTANDARD LVCMOS33 [get_ports IO_B34_LP6]
set_property PACKAGE_PIN C20 [get_ports {IO_B35_LP[1]}]
set_property PACKAGE_PIN B20 [get_ports {IO_B35_LN[1]}]
set_property PACKAGE_PIN A20 [get_ports {IO_B35_LN[2]}]
set_property PACKAGE_PIN B19 [get_ports {IO_B35_LP[2]}]
set_property PACKAGE_PIN E17 [get_ports {IO_B35_LP[3]}]
set_property PACKAGE_PIN D18 [get_ports {IO_B35_LN[3]}]
set_property PACKAGE_PIN D19 [get_ports {IO_B35_LP[4]}]
set_property PACKAGE_PIN D20 [get_ports {IO_B35_LN[4]}]
set_property PACKAGE_PIN E18 [get_ports {IO_B35_LP[5]}]
set_property PACKAGE_PIN E19 [get_ports {IO_B35_LN[5]}]
set_property PACKAGE_PIN F16 [get_ports {IO_B35_LP[6]}]
set_property PACKAGE_PIN F17 [get_ports {IO_B35_LN[6]}]
set_property PACKAGE_PIN M19 [get_ports {IO_B35_LP[7]}]
set_property PACKAGE_PIN M20 [get_ports {IO_B35_LN[7]}]
set_property PACKAGE_PIN M17 [get_ports {IO_B35_LP[8]}]
set_property PACKAGE_PIN M18 [get_ports {IO_B35_LN[8]}]
set_property PACKAGE_PIN L19 [get_ports {IO_B35_LP[9]}]
set_property PACKAGE_PIN L20 [get_ports {IO_B35_LN[9]}]
set_property PACKAGE_PIN K19 [get_ports {IO_B35_LP[10]}]
set_property PACKAGE_PIN J19 [get_ports {IO_B35_LN[10]}]
set_property PACKAGE_PIN L16 [get_ports {IO_B35_LP[11]}]
set_property PACKAGE_PIN L17 [get_ports {IO_B35_LN[11]}]
set_property PACKAGE_PIN K17 [get_ports {IO_B35_LP[12]}]
set_property PACKAGE_PIN K18 [get_ports {IO_B35_LN[12]}]
set_property PACKAGE_PIN H16 [get_ports {IO_B35_LP[13]}]
set_property PACKAGE_PIN H17 [get_ports {IO_B35_LN[13]}]
set_property PACKAGE_PIN J18 [get_ports {IO_B35_LP[14]}]
set_property PACKAGE_PIN H18 [get_ports {IO_B35_LN[14]}]
set_property PACKAGE_PIN F19 [get_ports {IO_B35_LP[15]}]
set_property PACKAGE_PIN F20 [get_ports {IO_B35_LN[15]}]
set_property PACKAGE_PIN G17 [get_ports {IO_B35_LP[16]}]
set_property PACKAGE_PIN G18 [get_ports {IO_B35_LN[16]}]
set_property PACKAGE_PIN J20 [get_ports {IO_B35_LP[17]}]
set_property PACKAGE_PIN H20 [get_ports {IO_B35_LN[17]}]
set_property PACKAGE_PIN G19 [get_ports {IO_B35_LP[18]}]
set_property PACKAGE_PIN G20 [get_ports {IO_B35_LN[18]}]
set_property PACKAGE_PIN H15 [get_ports {IO_B35_LP[19]}]
set_property PACKAGE_PIN G15 [get_ports {IO_B35_LN[19]}]
set_property PACKAGE_PIN K14 [get_ports {IO_B35_LP[20]}]
set_property PACKAGE_PIN J14 [get_ports {IO_B35_LN[20]}]
set_property PACKAGE_PIN N15 [get_ports {IO_B35_LP[21]}]
set_property PACKAGE_PIN N16 [get_ports {IO_B35_LN[21]}]
set_property PACKAGE_PIN L14 [get_ports {IO_B35_LP[22]}]
set_property PACKAGE_PIN L15 [get_ports {IO_B35_LN[22]}]
set_property PACKAGE_PIN M14 [get_ports {IO_B35_LP[23]}]
set_property PACKAGE_PIN M15 [get_ports {IO_B35_LN[23]}]
set_property PACKAGE_PIN K16 [get_ports {IO_B35_LP[24]}]
set_property PACKAGE_PIN J16 [get_ports {IO_B35_LN[24]}]
set_property IOSTANDARD LVCMOS33 [get_ports {SW[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {SW[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {SW[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {SW[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports HDMI_INTn]
set_property PACKAGE_PIN W19 [get_ports HDMI_INTn]
set_property IOSTANDARD LVCMOS33 [get_ports I2S_FSYNC_OUT]
set_property IOSTANDARD LVCMOS33 [get_ports I2S_SCLK]
set_property IOSTANDARD LVCMOS33 [get_ports I2S_DOUT]
set_property PACKAGE_PIN V17 [get_ports I2S_DOUT]
set_property PACKAGE_PIN T17 [get_ports I2S_SCLK]
set_property PACKAGE_PIN R18 [get_ports I2S_FSYNC_OUT]
set_property PACKAGE_PIN R19 [get_ports {SW[0]}]
set_property PACKAGE_PIN T19 [get_ports {SW[1]}]
set_property PACKAGE_PIN G14 [get_ports {SW[2]}]
set_property PACKAGE_PIN J15 [get_ports {SW[3]}]
#set_property PACKAGE_PIN Y16 [get_ports {LEDS[0]}]
#set_property PACKAGE_PIN Y17 [get_ports {LEDS[1]}]
set_property PACKAGE_PIN R14 [get_ports {LEDS[2]}]

set_property PACKAGE_PIN Y9 [get_ports {ADC_CK}]
set_property PACKAGE_PIN Y6 [get_ports {AD[11]}]
set_property PACKAGE_PIN V8 [get_ports {AD[10]}]
set_property PACKAGE_PIN V10 [get_ports {AD[9]}]
set_property PACKAGE_PIN T11 [get_ports {AD[8]}]
set_property PACKAGE_PIN W8 [get_ports {AD[7]}]
set_property PACKAGE_PIN T10 [get_ports {AD[6]}]
set_property PACKAGE_PIN T12 [get_ports {AD[5]}]
set_property PACKAGE_PIN U13 [get_ports {AD[4]}]
set_property PACKAGE_PIN U12 [get_ports {AD[3]}]
set_property PACKAGE_PIN V13 [get_ports {AD[2]}]
set_property PACKAGE_PIN V12 [get_ports {AD[1]}]
set_property PACKAGE_PIN W13 [get_ports {AD[0]}]
set_property PACKAGE_PIN V11 [get_ports {OFA}]
set_property PACKAGE_PIN U10 [get_ports {MUX}]
set_property PACKAGE_PIN Y16 [get_ports {SHDNA}]
set_property PACKAGE_PIN Y17 [get_ports {SHDNB}]
set_property IOSTANDARD LVCMOS33 [get_ports {ADC_CK}]
set_property IOSTANDARD LVCMOS33 [get_ports {AD[*]}]
set_property IOSTANDARD LVCMOS33 [get_ports {SHDNA}]
set_property IOSTANDARD LVCMOS33 [get_ports {SHDNB}]
set_property IOSTANDARD LVCMOS33 [get_ports {MUX}]
set_property IOSTANDARD LVCMOS33 [get_ports {OFA}]

create_clock -name adck -period 25.0 [get_ports ADC_CK]

set_property CFGBVS VCCO [current_design]
set_property CONFIG_VOLTAGE 3.3 [current_design]

create_debug_core u_ila_0 ila
set_property ALL_PROBE_SAME_MU true [get_debug_cores u_ila_0]
set_property ALL_PROBE_SAME_MU_CNT 1 [get_debug_cores u_ila_0]
set_property C_ADV_TRIGGER false [get_debug_cores u_ila_0]
set_property C_DATA_DEPTH 2048 [get_debug_cores u_ila_0]
set_property C_EN_STRG_QUAL false [get_debug_cores u_ila_0]
set_property C_INPUT_PIPE_STAGES 1 [get_debug_cores u_ila_0]
set_property C_TRIGIN_EN false [get_debug_cores u_ila_0]
set_property C_TRIGOUT_EN false [get_debug_cores u_ila_0]
set_property port_width 1 [get_debug_ports u_ila_0/clk]
connect_debug_port u_ila_0/clk [get_nets [list design_1_i/processing_system7_0/inst/FCLK_CLK0]]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe0]
set_property port_width 4 [get_debug_ports u_ila_0/probe0]
connect_debug_port u_ila_0/probe0 [get_nets [list {design_1_i/axi_dma_0_m_axi_addr_V_AWQOS[0]} {design_1_i/axi_dma_0_m_axi_addr_V_AWQOS[1]} {design_1_i/axi_dma_0_m_axi_addr_V_AWQOS[2]} {design_1_i/axi_dma_0_m_axi_addr_V_AWQOS[3]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe1]
set_property port_width 2 [get_debug_ports u_ila_0/probe1]
connect_debug_port u_ila_0/probe1 [get_nets [list {design_1_i/axi_dma_0_m_axi_addr_V_RRESP[0]} {design_1_i/axi_dma_0_m_axi_addr_V_RRESP[1]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe2]
set_property port_width 4 [get_debug_ports u_ila_0/probe2]
connect_debug_port u_ila_0/probe2 [get_nets [list {design_1_i/axi_dma_0_m_axi_addr_V_AWREGION[0]} {design_1_i/axi_dma_0_m_axi_addr_V_AWREGION[1]} {design_1_i/axi_dma_0_m_axi_addr_V_AWREGION[2]} {design_1_i/axi_dma_0_m_axi_addr_V_AWREGION[3]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe3]
set_property port_width 2 [get_debug_ports u_ila_0/probe3]
connect_debug_port u_ila_0/probe3 [get_nets [list {design_1_i/axi_dma_0_m_axi_addr_V_BRESP[0]} {design_1_i/axi_dma_0_m_axi_addr_V_BRESP[1]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe4]
set_property port_width 64 [get_debug_ports u_ila_0/probe4]
connect_debug_port u_ila_0/probe4 [get_nets [list {design_1_i/axi_dma_0_m_axi_addr_V_RDATA[0]} {design_1_i/axi_dma_0_m_axi_addr_V_RDATA[1]} {design_1_i/axi_dma_0_m_axi_addr_V_RDATA[2]} {design_1_i/axi_dma_0_m_axi_addr_V_RDATA[3]} {design_1_i/axi_dma_0_m_axi_addr_V_RDATA[4]} {design_1_i/axi_dma_0_m_axi_addr_V_RDATA[5]} {design_1_i/axi_dma_0_m_axi_addr_V_RDATA[6]} {design_1_i/axi_dma_0_m_axi_addr_V_RDATA[7]} {design_1_i/axi_dma_0_m_axi_addr_V_RDATA[8]} {design_1_i/axi_dma_0_m_axi_addr_V_RDATA[9]} {design_1_i/axi_dma_0_m_axi_addr_V_RDATA[10]} {design_1_i/axi_dma_0_m_axi_addr_V_RDATA[11]} {design_1_i/axi_dma_0_m_axi_addr_V_RDATA[12]} {design_1_i/axi_dma_0_m_axi_addr_V_RDATA[13]} {design_1_i/axi_dma_0_m_axi_addr_V_RDATA[14]} {design_1_i/axi_dma_0_m_axi_addr_V_RDATA[15]} {design_1_i/axi_dma_0_m_axi_addr_V_RDATA[16]} {design_1_i/axi_dma_0_m_axi_addr_V_RDATA[17]} {design_1_i/axi_dma_0_m_axi_addr_V_RDATA[18]} {design_1_i/axi_dma_0_m_axi_addr_V_RDATA[19]} {design_1_i/axi_dma_0_m_axi_addr_V_RDATA[20]} {design_1_i/axi_dma_0_m_axi_addr_V_RDATA[21]} {design_1_i/axi_dma_0_m_axi_addr_V_RDATA[22]} {design_1_i/axi_dma_0_m_axi_addr_V_RDATA[23]} {design_1_i/axi_dma_0_m_axi_addr_V_RDATA[24]} {design_1_i/axi_dma_0_m_axi_addr_V_RDATA[25]} {design_1_i/axi_dma_0_m_axi_addr_V_RDATA[26]} {design_1_i/axi_dma_0_m_axi_addr_V_RDATA[27]} {design_1_i/axi_dma_0_m_axi_addr_V_RDATA[28]} {design_1_i/axi_dma_0_m_axi_addr_V_RDATA[29]} {design_1_i/axi_dma_0_m_axi_addr_V_RDATA[30]} {design_1_i/axi_dma_0_m_axi_addr_V_RDATA[31]} {design_1_i/axi_dma_0_m_axi_addr_V_RDATA[32]} {design_1_i/axi_dma_0_m_axi_addr_V_RDATA[33]} {design_1_i/axi_dma_0_m_axi_addr_V_RDATA[34]} {design_1_i/axi_dma_0_m_axi_addr_V_RDATA[35]} {design_1_i/axi_dma_0_m_axi_addr_V_RDATA[36]} {design_1_i/axi_dma_0_m_axi_addr_V_RDATA[37]} {design_1_i/axi_dma_0_m_axi_addr_V_RDATA[38]} {design_1_i/axi_dma_0_m_axi_addr_V_RDATA[39]} {design_1_i/axi_dma_0_m_axi_addr_V_RDATA[40]} {design_1_i/axi_dma_0_m_axi_addr_V_RDATA[41]} {design_1_i/axi_dma_0_m_axi_addr_V_RDATA[42]} {design_1_i/axi_dma_0_m_axi_addr_V_RDATA[43]} {design_1_i/axi_dma_0_m_axi_addr_V_RDATA[44]} {design_1_i/axi_dma_0_m_axi_addr_V_RDATA[45]} {design_1_i/axi_dma_0_m_axi_addr_V_RDATA[46]} {design_1_i/axi_dma_0_m_axi_addr_V_RDATA[47]} {design_1_i/axi_dma_0_m_axi_addr_V_RDATA[48]} {design_1_i/axi_dma_0_m_axi_addr_V_RDATA[49]} {design_1_i/axi_dma_0_m_axi_addr_V_RDATA[50]} {design_1_i/axi_dma_0_m_axi_addr_V_RDATA[51]} {design_1_i/axi_dma_0_m_axi_addr_V_RDATA[52]} {design_1_i/axi_dma_0_m_axi_addr_V_RDATA[53]} {design_1_i/axi_dma_0_m_axi_addr_V_RDATA[54]} {design_1_i/axi_dma_0_m_axi_addr_V_RDATA[55]} {design_1_i/axi_dma_0_m_axi_addr_V_RDATA[56]} {design_1_i/axi_dma_0_m_axi_addr_V_RDATA[57]} {design_1_i/axi_dma_0_m_axi_addr_V_RDATA[58]} {design_1_i/axi_dma_0_m_axi_addr_V_RDATA[59]} {design_1_i/axi_dma_0_m_axi_addr_V_RDATA[60]} {design_1_i/axi_dma_0_m_axi_addr_V_RDATA[61]} {design_1_i/axi_dma_0_m_axi_addr_V_RDATA[62]} {design_1_i/axi_dma_0_m_axi_addr_V_RDATA[63]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe5]
set_property port_width 32 [get_debug_ports u_ila_0/probe5]
connect_debug_port u_ila_0/probe5 [get_nets [list {design_1_i/axi_dma_0_m_axi_addr_V_ARADDR[0]} {design_1_i/axi_dma_0_m_axi_addr_V_ARADDR[1]} {design_1_i/axi_dma_0_m_axi_addr_V_ARADDR[2]} {design_1_i/axi_dma_0_m_axi_addr_V_ARADDR[3]} {design_1_i/axi_dma_0_m_axi_addr_V_ARADDR[4]} {design_1_i/axi_dma_0_m_axi_addr_V_ARADDR[5]} {design_1_i/axi_dma_0_m_axi_addr_V_ARADDR[6]} {design_1_i/axi_dma_0_m_axi_addr_V_ARADDR[7]} {design_1_i/axi_dma_0_m_axi_addr_V_ARADDR[8]} {design_1_i/axi_dma_0_m_axi_addr_V_ARADDR[9]} {design_1_i/axi_dma_0_m_axi_addr_V_ARADDR[10]} {design_1_i/axi_dma_0_m_axi_addr_V_ARADDR[11]} {design_1_i/axi_dma_0_m_axi_addr_V_ARADDR[12]} {design_1_i/axi_dma_0_m_axi_addr_V_ARADDR[13]} {design_1_i/axi_dma_0_m_axi_addr_V_ARADDR[14]} {design_1_i/axi_dma_0_m_axi_addr_V_ARADDR[15]} {design_1_i/axi_dma_0_m_axi_addr_V_ARADDR[16]} {design_1_i/axi_dma_0_m_axi_addr_V_ARADDR[17]} {design_1_i/axi_dma_0_m_axi_addr_V_ARADDR[18]} {design_1_i/axi_dma_0_m_axi_addr_V_ARADDR[19]} {design_1_i/axi_dma_0_m_axi_addr_V_ARADDR[20]} {design_1_i/axi_dma_0_m_axi_addr_V_ARADDR[21]} {design_1_i/axi_dma_0_m_axi_addr_V_ARADDR[22]} {design_1_i/axi_dma_0_m_axi_addr_V_ARADDR[23]} {design_1_i/axi_dma_0_m_axi_addr_V_ARADDR[24]} {design_1_i/axi_dma_0_m_axi_addr_V_ARADDR[25]} {design_1_i/axi_dma_0_m_axi_addr_V_ARADDR[26]} {design_1_i/axi_dma_0_m_axi_addr_V_ARADDR[27]} {design_1_i/axi_dma_0_m_axi_addr_V_ARADDR[28]} {design_1_i/axi_dma_0_m_axi_addr_V_ARADDR[29]} {design_1_i/axi_dma_0_m_axi_addr_V_ARADDR[30]} {design_1_i/axi_dma_0_m_axi_addr_V_ARADDR[31]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe6]
set_property port_width 32 [get_debug_ports u_ila_0/probe6]
connect_debug_port u_ila_0/probe6 [get_nets [list {design_1_i/processing_system7_0_axi_periph_M00_AXI_ARADDR[0]} {design_1_i/processing_system7_0_axi_periph_M00_AXI_ARADDR[1]} {design_1_i/processing_system7_0_axi_periph_M00_AXI_ARADDR[2]} {design_1_i/processing_system7_0_axi_periph_M00_AXI_ARADDR[3]} {design_1_i/processing_system7_0_axi_periph_M00_AXI_ARADDR[4]} {design_1_i/processing_system7_0_axi_periph_M00_AXI_ARADDR[5]} {design_1_i/processing_system7_0_axi_periph_M00_AXI_ARADDR[6]} {design_1_i/processing_system7_0_axi_periph_M00_AXI_ARADDR[7]} {design_1_i/processing_system7_0_axi_periph_M00_AXI_ARADDR[8]} {design_1_i/processing_system7_0_axi_periph_M00_AXI_ARADDR[9]} {design_1_i/processing_system7_0_axi_periph_M00_AXI_ARADDR[10]} {design_1_i/processing_system7_0_axi_periph_M00_AXI_ARADDR[11]} {design_1_i/processing_system7_0_axi_periph_M00_AXI_ARADDR[12]} {design_1_i/processing_system7_0_axi_periph_M00_AXI_ARADDR[13]} {design_1_i/processing_system7_0_axi_periph_M00_AXI_ARADDR[14]} {design_1_i/processing_system7_0_axi_periph_M00_AXI_ARADDR[15]} {design_1_i/processing_system7_0_axi_periph_M00_AXI_ARADDR[16]} {design_1_i/processing_system7_0_axi_periph_M00_AXI_ARADDR[17]} {design_1_i/processing_system7_0_axi_periph_M00_AXI_ARADDR[18]} {design_1_i/processing_system7_0_axi_periph_M00_AXI_ARADDR[19]} {design_1_i/processing_system7_0_axi_periph_M00_AXI_ARADDR[20]} {design_1_i/processing_system7_0_axi_periph_M00_AXI_ARADDR[21]} {design_1_i/processing_system7_0_axi_periph_M00_AXI_ARADDR[22]} {design_1_i/processing_system7_0_axi_periph_M00_AXI_ARADDR[23]} {design_1_i/processing_system7_0_axi_periph_M00_AXI_ARADDR[24]} {design_1_i/processing_system7_0_axi_periph_M00_AXI_ARADDR[25]} {design_1_i/processing_system7_0_axi_periph_M00_AXI_ARADDR[26]} {design_1_i/processing_system7_0_axi_periph_M00_AXI_ARADDR[27]} {design_1_i/processing_system7_0_axi_periph_M00_AXI_ARADDR[28]} {design_1_i/processing_system7_0_axi_periph_M00_AXI_ARADDR[29]} {design_1_i/processing_system7_0_axi_periph_M00_AXI_ARADDR[30]} {design_1_i/processing_system7_0_axi_periph_M00_AXI_ARADDR[31]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe7]
set_property port_width 2 [get_debug_ports u_ila_0/probe7]
connect_debug_port u_ila_0/probe7 [get_nets [list {design_1_i/axi_dma_0_m_axi_addr_V_ARBURST[0]} {design_1_i/axi_dma_0_m_axi_addr_V_ARBURST[1]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe8]
set_property port_width 8 [get_debug_ports u_ila_0/probe8]
connect_debug_port u_ila_0/probe8 [get_nets [list {design_1_i/axi_dma_0_m_axi_addr_V_WSTRB[0]} {design_1_i/axi_dma_0_m_axi_addr_V_WSTRB[1]} {design_1_i/axi_dma_0_m_axi_addr_V_WSTRB[2]} {design_1_i/axi_dma_0_m_axi_addr_V_WSTRB[3]} {design_1_i/axi_dma_0_m_axi_addr_V_WSTRB[4]} {design_1_i/axi_dma_0_m_axi_addr_V_WSTRB[5]} {design_1_i/axi_dma_0_m_axi_addr_V_WSTRB[6]} {design_1_i/axi_dma_0_m_axi_addr_V_WSTRB[7]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe9]
set_property port_width 3 [get_debug_ports u_ila_0/probe9]
connect_debug_port u_ila_0/probe9 [get_nets [list {design_1_i/axi_dma_0_m_axi_addr_V_AWSIZE[0]} {design_1_i/axi_dma_0_m_axi_addr_V_AWSIZE[1]} {design_1_i/axi_dma_0_m_axi_addr_V_AWSIZE[2]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe10]
set_property port_width 64 [get_debug_ports u_ila_0/probe10]
connect_debug_port u_ila_0/probe10 [get_nets [list {design_1_i/axi_dma_0_m_axi_addr_V_WDATA[0]} {design_1_i/axi_dma_0_m_axi_addr_V_WDATA[1]} {design_1_i/axi_dma_0_m_axi_addr_V_WDATA[2]} {design_1_i/axi_dma_0_m_axi_addr_V_WDATA[3]} {design_1_i/axi_dma_0_m_axi_addr_V_WDATA[4]} {design_1_i/axi_dma_0_m_axi_addr_V_WDATA[5]} {design_1_i/axi_dma_0_m_axi_addr_V_WDATA[6]} {design_1_i/axi_dma_0_m_axi_addr_V_WDATA[7]} {design_1_i/axi_dma_0_m_axi_addr_V_WDATA[8]} {design_1_i/axi_dma_0_m_axi_addr_V_WDATA[9]} {design_1_i/axi_dma_0_m_axi_addr_V_WDATA[10]} {design_1_i/axi_dma_0_m_axi_addr_V_WDATA[11]} {design_1_i/axi_dma_0_m_axi_addr_V_WDATA[12]} {design_1_i/axi_dma_0_m_axi_addr_V_WDATA[13]} {design_1_i/axi_dma_0_m_axi_addr_V_WDATA[14]} {design_1_i/axi_dma_0_m_axi_addr_V_WDATA[15]} {design_1_i/axi_dma_0_m_axi_addr_V_WDATA[16]} {design_1_i/axi_dma_0_m_axi_addr_V_WDATA[17]} {design_1_i/axi_dma_0_m_axi_addr_V_WDATA[18]} {design_1_i/axi_dma_0_m_axi_addr_V_WDATA[19]} {design_1_i/axi_dma_0_m_axi_addr_V_WDATA[20]} {design_1_i/axi_dma_0_m_axi_addr_V_WDATA[21]} {design_1_i/axi_dma_0_m_axi_addr_V_WDATA[22]} {design_1_i/axi_dma_0_m_axi_addr_V_WDATA[23]} {design_1_i/axi_dma_0_m_axi_addr_V_WDATA[24]} {design_1_i/axi_dma_0_m_axi_addr_V_WDATA[25]} {design_1_i/axi_dma_0_m_axi_addr_V_WDATA[26]} {design_1_i/axi_dma_0_m_axi_addr_V_WDATA[27]} {design_1_i/axi_dma_0_m_axi_addr_V_WDATA[28]} {design_1_i/axi_dma_0_m_axi_addr_V_WDATA[29]} {design_1_i/axi_dma_0_m_axi_addr_V_WDATA[30]} {design_1_i/axi_dma_0_m_axi_addr_V_WDATA[31]} {design_1_i/axi_dma_0_m_axi_addr_V_WDATA[32]} {design_1_i/axi_dma_0_m_axi_addr_V_WDATA[33]} {design_1_i/axi_dma_0_m_axi_addr_V_WDATA[34]} {design_1_i/axi_dma_0_m_axi_addr_V_WDATA[35]} {design_1_i/axi_dma_0_m_axi_addr_V_WDATA[36]} {design_1_i/axi_dma_0_m_axi_addr_V_WDATA[37]} {design_1_i/axi_dma_0_m_axi_addr_V_WDATA[38]} {design_1_i/axi_dma_0_m_axi_addr_V_WDATA[39]} {design_1_i/axi_dma_0_m_axi_addr_V_WDATA[40]} {design_1_i/axi_dma_0_m_axi_addr_V_WDATA[41]} {design_1_i/axi_dma_0_m_axi_addr_V_WDATA[42]} {design_1_i/axi_dma_0_m_axi_addr_V_WDATA[43]} {design_1_i/axi_dma_0_m_axi_addr_V_WDATA[44]} {design_1_i/axi_dma_0_m_axi_addr_V_WDATA[45]} {design_1_i/axi_dma_0_m_axi_addr_V_WDATA[46]} {design_1_i/axi_dma_0_m_axi_addr_V_WDATA[47]} {design_1_i/axi_dma_0_m_axi_addr_V_WDATA[48]} {design_1_i/axi_dma_0_m_axi_addr_V_WDATA[49]} {design_1_i/axi_dma_0_m_axi_addr_V_WDATA[50]} {design_1_i/axi_dma_0_m_axi_addr_V_WDATA[51]} {design_1_i/axi_dma_0_m_axi_addr_V_WDATA[52]} {design_1_i/axi_dma_0_m_axi_addr_V_WDATA[53]} {design_1_i/axi_dma_0_m_axi_addr_V_WDATA[54]} {design_1_i/axi_dma_0_m_axi_addr_V_WDATA[55]} {design_1_i/axi_dma_0_m_axi_addr_V_WDATA[56]} {design_1_i/axi_dma_0_m_axi_addr_V_WDATA[57]} {design_1_i/axi_dma_0_m_axi_addr_V_WDATA[58]} {design_1_i/axi_dma_0_m_axi_addr_V_WDATA[59]} {design_1_i/axi_dma_0_m_axi_addr_V_WDATA[60]} {design_1_i/axi_dma_0_m_axi_addr_V_WDATA[61]} {design_1_i/axi_dma_0_m_axi_addr_V_WDATA[62]} {design_1_i/axi_dma_0_m_axi_addr_V_WDATA[63]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe11]
set_property port_width 32 [get_debug_ports u_ila_0/probe11]
connect_debug_port u_ila_0/probe11 [get_nets [list {design_1_i/processing_system7_0_axi_periph_M00_AXI_AWADDR[0]} {design_1_i/processing_system7_0_axi_periph_M00_AXI_AWADDR[1]} {design_1_i/processing_system7_0_axi_periph_M00_AXI_AWADDR[2]} {design_1_i/processing_system7_0_axi_periph_M00_AXI_AWADDR[3]} {design_1_i/processing_system7_0_axi_periph_M00_AXI_AWADDR[4]} {design_1_i/processing_system7_0_axi_periph_M00_AXI_AWADDR[5]} {design_1_i/processing_system7_0_axi_periph_M00_AXI_AWADDR[6]} {design_1_i/processing_system7_0_axi_periph_M00_AXI_AWADDR[7]} {design_1_i/processing_system7_0_axi_periph_M00_AXI_AWADDR[8]} {design_1_i/processing_system7_0_axi_periph_M00_AXI_AWADDR[9]} {design_1_i/processing_system7_0_axi_periph_M00_AXI_AWADDR[10]} {design_1_i/processing_system7_0_axi_periph_M00_AXI_AWADDR[11]} {design_1_i/processing_system7_0_axi_periph_M00_AXI_AWADDR[12]} {design_1_i/processing_system7_0_axi_periph_M00_AXI_AWADDR[13]} {design_1_i/processing_system7_0_axi_periph_M00_AXI_AWADDR[14]} {design_1_i/processing_system7_0_axi_periph_M00_AXI_AWADDR[15]} {design_1_i/processing_system7_0_axi_periph_M00_AXI_AWADDR[16]} {design_1_i/processing_system7_0_axi_periph_M00_AXI_AWADDR[17]} {design_1_i/processing_system7_0_axi_periph_M00_AXI_AWADDR[18]} {design_1_i/processing_system7_0_axi_periph_M00_AXI_AWADDR[19]} {design_1_i/processing_system7_0_axi_periph_M00_AXI_AWADDR[20]} {design_1_i/processing_system7_0_axi_periph_M00_AXI_AWADDR[21]} {design_1_i/processing_system7_0_axi_periph_M00_AXI_AWADDR[22]} {design_1_i/processing_system7_0_axi_periph_M00_AXI_AWADDR[23]} {design_1_i/processing_system7_0_axi_periph_M00_AXI_AWADDR[24]} {design_1_i/processing_system7_0_axi_periph_M00_AXI_AWADDR[25]} {design_1_i/processing_system7_0_axi_periph_M00_AXI_AWADDR[26]} {design_1_i/processing_system7_0_axi_periph_M00_AXI_AWADDR[27]} {design_1_i/processing_system7_0_axi_periph_M00_AXI_AWADDR[28]} {design_1_i/processing_system7_0_axi_periph_M00_AXI_AWADDR[29]} {design_1_i/processing_system7_0_axi_periph_M00_AXI_AWADDR[30]} {design_1_i/processing_system7_0_axi_periph_M00_AXI_AWADDR[31]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe12]
set_property port_width 32 [get_debug_ports u_ila_0/probe12]
connect_debug_port u_ila_0/probe12 [get_nets [list {design_1_i/processing_system7_0_axi_periph_M00_AXI_RDATA[0]} {design_1_i/processing_system7_0_axi_periph_M00_AXI_RDATA[1]} {design_1_i/processing_system7_0_axi_periph_M00_AXI_RDATA[2]} {design_1_i/processing_system7_0_axi_periph_M00_AXI_RDATA[3]} {design_1_i/processing_system7_0_axi_periph_M00_AXI_RDATA[4]} {design_1_i/processing_system7_0_axi_periph_M00_AXI_RDATA[5]} {design_1_i/processing_system7_0_axi_periph_M00_AXI_RDATA[6]} {design_1_i/processing_system7_0_axi_periph_M00_AXI_RDATA[7]} {design_1_i/processing_system7_0_axi_periph_M00_AXI_RDATA[8]} {design_1_i/processing_system7_0_axi_periph_M00_AXI_RDATA[9]} {design_1_i/processing_system7_0_axi_periph_M00_AXI_RDATA[10]} {design_1_i/processing_system7_0_axi_periph_M00_AXI_RDATA[11]} {design_1_i/processing_system7_0_axi_periph_M00_AXI_RDATA[12]} {design_1_i/processing_system7_0_axi_periph_M00_AXI_RDATA[13]} {design_1_i/processing_system7_0_axi_periph_M00_AXI_RDATA[14]} {design_1_i/processing_system7_0_axi_periph_M00_AXI_RDATA[15]} {design_1_i/processing_system7_0_axi_periph_M00_AXI_RDATA[16]} {design_1_i/processing_system7_0_axi_periph_M00_AXI_RDATA[17]} {design_1_i/processing_system7_0_axi_periph_M00_AXI_RDATA[18]} {design_1_i/processing_system7_0_axi_periph_M00_AXI_RDATA[19]} {design_1_i/processing_system7_0_axi_periph_M00_AXI_RDATA[20]} {design_1_i/processing_system7_0_axi_periph_M00_AXI_RDATA[21]} {design_1_i/processing_system7_0_axi_periph_M00_AXI_RDATA[22]} {design_1_i/processing_system7_0_axi_periph_M00_AXI_RDATA[23]} {design_1_i/processing_system7_0_axi_periph_M00_AXI_RDATA[24]} {design_1_i/processing_system7_0_axi_periph_M00_AXI_RDATA[25]} {design_1_i/processing_system7_0_axi_periph_M00_AXI_RDATA[26]} {design_1_i/processing_system7_0_axi_periph_M00_AXI_RDATA[27]} {design_1_i/processing_system7_0_axi_periph_M00_AXI_RDATA[28]} {design_1_i/processing_system7_0_axi_periph_M00_AXI_RDATA[29]} {design_1_i/processing_system7_0_axi_periph_M00_AXI_RDATA[30]} {design_1_i/processing_system7_0_axi_periph_M00_AXI_RDATA[31]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe13]
set_property port_width 2 [get_debug_ports u_ila_0/probe13]
connect_debug_port u_ila_0/probe13 [get_nets [list {design_1_i/processing_system7_0_axi_periph_M00_AXI_BRESP[0]} {design_1_i/processing_system7_0_axi_periph_M00_AXI_BRESP[1]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe14]
set_property port_width 32 [get_debug_ports u_ila_0/probe14]
connect_debug_port u_ila_0/probe14 [get_nets [list {design_1_i/processing_system7_0_axi_periph_M00_AXI_WDATA[0]} {design_1_i/processing_system7_0_axi_periph_M00_AXI_WDATA[1]} {design_1_i/processing_system7_0_axi_periph_M00_AXI_WDATA[2]} {design_1_i/processing_system7_0_axi_periph_M00_AXI_WDATA[3]} {design_1_i/processing_system7_0_axi_periph_M00_AXI_WDATA[4]} {design_1_i/processing_system7_0_axi_periph_M00_AXI_WDATA[5]} {design_1_i/processing_system7_0_axi_periph_M00_AXI_WDATA[6]} {design_1_i/processing_system7_0_axi_periph_M00_AXI_WDATA[7]} {design_1_i/processing_system7_0_axi_periph_M00_AXI_WDATA[8]} {design_1_i/processing_system7_0_axi_periph_M00_AXI_WDATA[9]} {design_1_i/processing_system7_0_axi_periph_M00_AXI_WDATA[10]} {design_1_i/processing_system7_0_axi_periph_M00_AXI_WDATA[11]} {design_1_i/processing_system7_0_axi_periph_M00_AXI_WDATA[12]} {design_1_i/processing_system7_0_axi_periph_M00_AXI_WDATA[13]} {design_1_i/processing_system7_0_axi_periph_M00_AXI_WDATA[14]} {design_1_i/processing_system7_0_axi_periph_M00_AXI_WDATA[15]} {design_1_i/processing_system7_0_axi_periph_M00_AXI_WDATA[16]} {design_1_i/processing_system7_0_axi_periph_M00_AXI_WDATA[17]} {design_1_i/processing_system7_0_axi_periph_M00_AXI_WDATA[18]} {design_1_i/processing_system7_0_axi_periph_M00_AXI_WDATA[19]} {design_1_i/processing_system7_0_axi_periph_M00_AXI_WDATA[20]} {design_1_i/processing_system7_0_axi_periph_M00_AXI_WDATA[21]} {design_1_i/processing_system7_0_axi_periph_M00_AXI_WDATA[22]} {design_1_i/processing_system7_0_axi_periph_M00_AXI_WDATA[23]} {design_1_i/processing_system7_0_axi_periph_M00_AXI_WDATA[24]} {design_1_i/processing_system7_0_axi_periph_M00_AXI_WDATA[25]} {design_1_i/processing_system7_0_axi_periph_M00_AXI_WDATA[26]} {design_1_i/processing_system7_0_axi_periph_M00_AXI_WDATA[27]} {design_1_i/processing_system7_0_axi_periph_M00_AXI_WDATA[28]} {design_1_i/processing_system7_0_axi_periph_M00_AXI_WDATA[29]} {design_1_i/processing_system7_0_axi_periph_M00_AXI_WDATA[30]} {design_1_i/processing_system7_0_axi_periph_M00_AXI_WDATA[31]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe15]
set_property port_width 2 [get_debug_ports u_ila_0/probe15]
connect_debug_port u_ila_0/probe15 [get_nets [list {design_1_i/processing_system7_0_axi_periph_M00_AXI_RRESP[0]} {design_1_i/processing_system7_0_axi_periph_M00_AXI_RRESP[1]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe16]
set_property port_width 64 [get_debug_ports u_ila_0/probe16]
connect_debug_port u_ila_0/probe16 [get_nets [list {design_1_i/axis_data_fifo_0_M_AXIS_TDATA[0]} {design_1_i/axis_data_fifo_0_M_AXIS_TDATA[1]} {design_1_i/axis_data_fifo_0_M_AXIS_TDATA[2]} {design_1_i/axis_data_fifo_0_M_AXIS_TDATA[3]} {design_1_i/axis_data_fifo_0_M_AXIS_TDATA[4]} {design_1_i/axis_data_fifo_0_M_AXIS_TDATA[5]} {design_1_i/axis_data_fifo_0_M_AXIS_TDATA[6]} {design_1_i/axis_data_fifo_0_M_AXIS_TDATA[7]} {design_1_i/axis_data_fifo_0_M_AXIS_TDATA[8]} {design_1_i/axis_data_fifo_0_M_AXIS_TDATA[9]} {design_1_i/axis_data_fifo_0_M_AXIS_TDATA[10]} {design_1_i/axis_data_fifo_0_M_AXIS_TDATA[11]} {design_1_i/axis_data_fifo_0_M_AXIS_TDATA[12]} {design_1_i/axis_data_fifo_0_M_AXIS_TDATA[13]} {design_1_i/axis_data_fifo_0_M_AXIS_TDATA[14]} {design_1_i/axis_data_fifo_0_M_AXIS_TDATA[15]} {design_1_i/axis_data_fifo_0_M_AXIS_TDATA[16]} {design_1_i/axis_data_fifo_0_M_AXIS_TDATA[17]} {design_1_i/axis_data_fifo_0_M_AXIS_TDATA[18]} {design_1_i/axis_data_fifo_0_M_AXIS_TDATA[19]} {design_1_i/axis_data_fifo_0_M_AXIS_TDATA[20]} {design_1_i/axis_data_fifo_0_M_AXIS_TDATA[21]} {design_1_i/axis_data_fifo_0_M_AXIS_TDATA[22]} {design_1_i/axis_data_fifo_0_M_AXIS_TDATA[23]} {design_1_i/axis_data_fifo_0_M_AXIS_TDATA[24]} {design_1_i/axis_data_fifo_0_M_AXIS_TDATA[25]} {design_1_i/axis_data_fifo_0_M_AXIS_TDATA[26]} {design_1_i/axis_data_fifo_0_M_AXIS_TDATA[27]} {design_1_i/axis_data_fifo_0_M_AXIS_TDATA[28]} {design_1_i/axis_data_fifo_0_M_AXIS_TDATA[29]} {design_1_i/axis_data_fifo_0_M_AXIS_TDATA[30]} {design_1_i/axis_data_fifo_0_M_AXIS_TDATA[31]} {design_1_i/axis_data_fifo_0_M_AXIS_TDATA[32]} {design_1_i/axis_data_fifo_0_M_AXIS_TDATA[33]} {design_1_i/axis_data_fifo_0_M_AXIS_TDATA[34]} {design_1_i/axis_data_fifo_0_M_AXIS_TDATA[35]} {design_1_i/axis_data_fifo_0_M_AXIS_TDATA[36]} {design_1_i/axis_data_fifo_0_M_AXIS_TDATA[37]} {design_1_i/axis_data_fifo_0_M_AXIS_TDATA[38]} {design_1_i/axis_data_fifo_0_M_AXIS_TDATA[39]} {design_1_i/axis_data_fifo_0_M_AXIS_TDATA[40]} {design_1_i/axis_data_fifo_0_M_AXIS_TDATA[41]} {design_1_i/axis_data_fifo_0_M_AXIS_TDATA[42]} {design_1_i/axis_data_fifo_0_M_AXIS_TDATA[43]} {design_1_i/axis_data_fifo_0_M_AXIS_TDATA[44]} {design_1_i/axis_data_fifo_0_M_AXIS_TDATA[45]} {design_1_i/axis_data_fifo_0_M_AXIS_TDATA[46]} {design_1_i/axis_data_fifo_0_M_AXIS_TDATA[47]} {design_1_i/axis_data_fifo_0_M_AXIS_TDATA[48]} {design_1_i/axis_data_fifo_0_M_AXIS_TDATA[49]} {design_1_i/axis_data_fifo_0_M_AXIS_TDATA[50]} {design_1_i/axis_data_fifo_0_M_AXIS_TDATA[51]} {design_1_i/axis_data_fifo_0_M_AXIS_TDATA[52]} {design_1_i/axis_data_fifo_0_M_AXIS_TDATA[53]} {design_1_i/axis_data_fifo_0_M_AXIS_TDATA[54]} {design_1_i/axis_data_fifo_0_M_AXIS_TDATA[55]} {design_1_i/axis_data_fifo_0_M_AXIS_TDATA[56]} {design_1_i/axis_data_fifo_0_M_AXIS_TDATA[57]} {design_1_i/axis_data_fifo_0_M_AXIS_TDATA[58]} {design_1_i/axis_data_fifo_0_M_AXIS_TDATA[59]} {design_1_i/axis_data_fifo_0_M_AXIS_TDATA[60]} {design_1_i/axis_data_fifo_0_M_AXIS_TDATA[61]} {design_1_i/axis_data_fifo_0_M_AXIS_TDATA[62]} {design_1_i/axis_data_fifo_0_M_AXIS_TDATA[63]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe17]
set_property port_width 4 [get_debug_ports u_ila_0/probe17]
connect_debug_port u_ila_0/probe17 [get_nets [list {design_1_i/axi_dma_0_m_axi_addr_V_ARCACHE[0]} {design_1_i/axi_dma_0_m_axi_addr_V_ARCACHE[1]} {design_1_i/axi_dma_0_m_axi_addr_V_ARCACHE[2]} {design_1_i/axi_dma_0_m_axi_addr_V_ARCACHE[3]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe18]
set_property port_width 4 [get_debug_ports u_ila_0/probe18]
connect_debug_port u_ila_0/probe18 [get_nets [list {design_1_i/axi_dma_0_m_axi_addr_V_ARQOS[0]} {design_1_i/axi_dma_0_m_axi_addr_V_ARQOS[1]} {design_1_i/axi_dma_0_m_axi_addr_V_ARQOS[2]} {design_1_i/axi_dma_0_m_axi_addr_V_ARQOS[3]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe19]
set_property port_width 32 [get_debug_ports u_ila_0/probe19]
connect_debug_port u_ila_0/probe19 [get_nets [list {design_1_i/axi_dma_0_m_axi_addr_V_AWADDR[0]} {design_1_i/axi_dma_0_m_axi_addr_V_AWADDR[1]} {design_1_i/axi_dma_0_m_axi_addr_V_AWADDR[2]} {design_1_i/axi_dma_0_m_axi_addr_V_AWADDR[3]} {design_1_i/axi_dma_0_m_axi_addr_V_AWADDR[4]} {design_1_i/axi_dma_0_m_axi_addr_V_AWADDR[5]} {design_1_i/axi_dma_0_m_axi_addr_V_AWADDR[6]} {design_1_i/axi_dma_0_m_axi_addr_V_AWADDR[7]} {design_1_i/axi_dma_0_m_axi_addr_V_AWADDR[8]} {design_1_i/axi_dma_0_m_axi_addr_V_AWADDR[9]} {design_1_i/axi_dma_0_m_axi_addr_V_AWADDR[10]} {design_1_i/axi_dma_0_m_axi_addr_V_AWADDR[11]} {design_1_i/axi_dma_0_m_axi_addr_V_AWADDR[12]} {design_1_i/axi_dma_0_m_axi_addr_V_AWADDR[13]} {design_1_i/axi_dma_0_m_axi_addr_V_AWADDR[14]} {design_1_i/axi_dma_0_m_axi_addr_V_AWADDR[15]} {design_1_i/axi_dma_0_m_axi_addr_V_AWADDR[16]} {design_1_i/axi_dma_0_m_axi_addr_V_AWADDR[17]} {design_1_i/axi_dma_0_m_axi_addr_V_AWADDR[18]} {design_1_i/axi_dma_0_m_axi_addr_V_AWADDR[19]} {design_1_i/axi_dma_0_m_axi_addr_V_AWADDR[20]} {design_1_i/axi_dma_0_m_axi_addr_V_AWADDR[21]} {design_1_i/axi_dma_0_m_axi_addr_V_AWADDR[22]} {design_1_i/axi_dma_0_m_axi_addr_V_AWADDR[23]} {design_1_i/axi_dma_0_m_axi_addr_V_AWADDR[24]} {design_1_i/axi_dma_0_m_axi_addr_V_AWADDR[25]} {design_1_i/axi_dma_0_m_axi_addr_V_AWADDR[26]} {design_1_i/axi_dma_0_m_axi_addr_V_AWADDR[27]} {design_1_i/axi_dma_0_m_axi_addr_V_AWADDR[28]} {design_1_i/axi_dma_0_m_axi_addr_V_AWADDR[29]} {design_1_i/axi_dma_0_m_axi_addr_V_AWADDR[30]} {design_1_i/axi_dma_0_m_axi_addr_V_AWADDR[31]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe20]
set_property port_width 3 [get_debug_ports u_ila_0/probe20]
connect_debug_port u_ila_0/probe20 [get_nets [list {design_1_i/axi_dma_0_m_axi_addr_V_AWPROT[0]} {design_1_i/axi_dma_0_m_axi_addr_V_AWPROT[1]} {design_1_i/axi_dma_0_m_axi_addr_V_AWPROT[2]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe21]
set_property port_width 2 [get_debug_ports u_ila_0/probe21]
connect_debug_port u_ila_0/probe21 [get_nets [list {design_1_i/axi_dma_0_m_axi_addr_V_AWLOCK[0]} {design_1_i/axi_dma_0_m_axi_addr_V_AWLOCK[1]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe22]
set_property port_width 4 [get_debug_ports u_ila_0/probe22]
connect_debug_port u_ila_0/probe22 [get_nets [list {design_1_i/axi_dma_0_m_axi_addr_V_ARREGION[0]} {design_1_i/axi_dma_0_m_axi_addr_V_ARREGION[1]} {design_1_i/axi_dma_0_m_axi_addr_V_ARREGION[2]} {design_1_i/axi_dma_0_m_axi_addr_V_ARREGION[3]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe23]
set_property port_width 8 [get_debug_ports u_ila_0/probe23]
connect_debug_port u_ila_0/probe23 [get_nets [list {design_1_i/axi_dma_0_m_axi_addr_V_ARLEN[0]} {design_1_i/axi_dma_0_m_axi_addr_V_ARLEN[1]} {design_1_i/axi_dma_0_m_axi_addr_V_ARLEN[2]} {design_1_i/axi_dma_0_m_axi_addr_V_ARLEN[3]} {design_1_i/axi_dma_0_m_axi_addr_V_ARLEN[4]} {design_1_i/axi_dma_0_m_axi_addr_V_ARLEN[5]} {design_1_i/axi_dma_0_m_axi_addr_V_ARLEN[6]} {design_1_i/axi_dma_0_m_axi_addr_V_ARLEN[7]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe24]
set_property port_width 3 [get_debug_ports u_ila_0/probe24]
connect_debug_port u_ila_0/probe24 [get_nets [list {design_1_i/axi_dma_0_m_axi_addr_V_ARSIZE[0]} {design_1_i/axi_dma_0_m_axi_addr_V_ARSIZE[1]} {design_1_i/axi_dma_0_m_axi_addr_V_ARSIZE[2]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe25]
set_property port_width 8 [get_debug_ports u_ila_0/probe25]
connect_debug_port u_ila_0/probe25 [get_nets [list {design_1_i/axi_dma_0_m_axi_addr_V_AWLEN[0]} {design_1_i/axi_dma_0_m_axi_addr_V_AWLEN[1]} {design_1_i/axi_dma_0_m_axi_addr_V_AWLEN[2]} {design_1_i/axi_dma_0_m_axi_addr_V_AWLEN[3]} {design_1_i/axi_dma_0_m_axi_addr_V_AWLEN[4]} {design_1_i/axi_dma_0_m_axi_addr_V_AWLEN[5]} {design_1_i/axi_dma_0_m_axi_addr_V_AWLEN[6]} {design_1_i/axi_dma_0_m_axi_addr_V_AWLEN[7]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe26]
set_property port_width 2 [get_debug_ports u_ila_0/probe26]
connect_debug_port u_ila_0/probe26 [get_nets [list {design_1_i/axi_dma_0_m_axi_addr_V_AWBURST[0]} {design_1_i/axi_dma_0_m_axi_addr_V_AWBURST[1]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe27]
set_property port_width 3 [get_debug_ports u_ila_0/probe27]
connect_debug_port u_ila_0/probe27 [get_nets [list {design_1_i/axi_dma_0_m_axi_addr_V_ARPROT[0]} {design_1_i/axi_dma_0_m_axi_addr_V_ARPROT[1]} {design_1_i/axi_dma_0_m_axi_addr_V_ARPROT[2]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe28]
set_property port_width 4 [get_debug_ports u_ila_0/probe28]
connect_debug_port u_ila_0/probe28 [get_nets [list {design_1_i/axi_dma_0_m_axi_addr_V_AWCACHE[0]} {design_1_i/axi_dma_0_m_axi_addr_V_AWCACHE[1]} {design_1_i/axi_dma_0_m_axi_addr_V_AWCACHE[2]} {design_1_i/axi_dma_0_m_axi_addr_V_AWCACHE[3]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe29]
set_property port_width 2 [get_debug_ports u_ila_0/probe29]
connect_debug_port u_ila_0/probe29 [get_nets [list {design_1_i/axi_dma_0_m_axi_addr_V_ARLOCK[0]} {design_1_i/axi_dma_0_m_axi_addr_V_ARLOCK[1]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe30]
set_property port_width 4 [get_debug_ports u_ila_0/probe30]
connect_debug_port u_ila_0/probe30 [get_nets [list {design_1_i/processing_system7_0_axi_periph_M00_AXI_WSTRB[0]} {design_1_i/processing_system7_0_axi_periph_M00_AXI_WSTRB[1]} {design_1_i/processing_system7_0_axi_periph_M00_AXI_WSTRB[2]} {design_1_i/processing_system7_0_axi_periph_M00_AXI_WSTRB[3]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe31]
set_property port_width 1 [get_debug_ports u_ila_0/probe31]
connect_debug_port u_ila_0/probe31 [get_nets [list design_1_i/axi_dma_0_m_axi_addr_V_ARREADY]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe32]
set_property port_width 1 [get_debug_ports u_ila_0/probe32]
connect_debug_port u_ila_0/probe32 [get_nets [list design_1_i/axi_dma_0_m_axi_addr_V_ARVALID]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe33]
set_property port_width 1 [get_debug_ports u_ila_0/probe33]
connect_debug_port u_ila_0/probe33 [get_nets [list design_1_i/axi_dma_0_m_axi_addr_V_AWREADY]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe34]
set_property port_width 1 [get_debug_ports u_ila_0/probe34]
connect_debug_port u_ila_0/probe34 [get_nets [list design_1_i/axi_dma_0_m_axi_addr_V_AWVALID]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe35]
set_property port_width 1 [get_debug_ports u_ila_0/probe35]
connect_debug_port u_ila_0/probe35 [get_nets [list design_1_i/axi_dma_0_m_axi_addr_V_BREADY]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe36]
set_property port_width 1 [get_debug_ports u_ila_0/probe36]
connect_debug_port u_ila_0/probe36 [get_nets [list design_1_i/axi_dma_0_m_axi_addr_V_BVALID]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe37]
set_property port_width 1 [get_debug_ports u_ila_0/probe37]
connect_debug_port u_ila_0/probe37 [get_nets [list design_1_i/axi_dma_0_m_axi_addr_V_RLAST]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe38]
set_property port_width 1 [get_debug_ports u_ila_0/probe38]
connect_debug_port u_ila_0/probe38 [get_nets [list design_1_i/axi_dma_0_m_axi_addr_V_RREADY]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe39]
set_property port_width 1 [get_debug_ports u_ila_0/probe39]
connect_debug_port u_ila_0/probe39 [get_nets [list design_1_i/axi_dma_0_m_axi_addr_V_RVALID]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe40]
set_property port_width 1 [get_debug_ports u_ila_0/probe40]
connect_debug_port u_ila_0/probe40 [get_nets [list design_1_i/axi_dma_0_m_axi_addr_V_WLAST]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe41]
set_property port_width 1 [get_debug_ports u_ila_0/probe41]
connect_debug_port u_ila_0/probe41 [get_nets [list design_1_i/axi_dma_0_m_axi_addr_V_WREADY]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe42]
set_property port_width 1 [get_debug_ports u_ila_0/probe42]
connect_debug_port u_ila_0/probe42 [get_nets [list design_1_i/axi_dma_0_m_axi_addr_V_WVALID]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe43]
set_property port_width 1 [get_debug_ports u_ila_0/probe43]
connect_debug_port u_ila_0/probe43 [get_nets [list design_1_i/axis_data_fifo_0_M_AXIS_TREADY]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe44]
set_property port_width 1 [get_debug_ports u_ila_0/probe44]
connect_debug_port u_ila_0/probe44 [get_nets [list design_1_i/axis_data_fifo_0_M_AXIS_TVALID]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe45]
set_property port_width 1 [get_debug_ports u_ila_0/probe45]
connect_debug_port u_ila_0/probe45 [get_nets [list design_1_i/processing_system7_0_axi_periph_M00_AXI_ARREADY]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe46]
set_property port_width 1 [get_debug_ports u_ila_0/probe46]
connect_debug_port u_ila_0/probe46 [get_nets [list design_1_i/processing_system7_0_axi_periph_M00_AXI_ARVALID]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe47]
set_property port_width 1 [get_debug_ports u_ila_0/probe47]
connect_debug_port u_ila_0/probe47 [get_nets [list design_1_i/processing_system7_0_axi_periph_M00_AXI_AWREADY]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe48]
set_property port_width 1 [get_debug_ports u_ila_0/probe48]
connect_debug_port u_ila_0/probe48 [get_nets [list design_1_i/processing_system7_0_axi_periph_M00_AXI_AWVALID]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe49]
set_property port_width 1 [get_debug_ports u_ila_0/probe49]
connect_debug_port u_ila_0/probe49 [get_nets [list design_1_i/processing_system7_0_axi_periph_M00_AXI_BREADY]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe50]
set_property port_width 1 [get_debug_ports u_ila_0/probe50]
connect_debug_port u_ila_0/probe50 [get_nets [list design_1_i/processing_system7_0_axi_periph_M00_AXI_BVALID]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe51]
set_property port_width 1 [get_debug_ports u_ila_0/probe51]
connect_debug_port u_ila_0/probe51 [get_nets [list design_1_i/processing_system7_0_axi_periph_M00_AXI_RREADY]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe52]
set_property port_width 1 [get_debug_ports u_ila_0/probe52]
connect_debug_port u_ila_0/probe52 [get_nets [list design_1_i/processing_system7_0_axi_periph_M00_AXI_RVALID]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe53]
set_property port_width 1 [get_debug_ports u_ila_0/probe53]
connect_debug_port u_ila_0/probe53 [get_nets [list design_1_i/processing_system7_0_axi_periph_M00_AXI_WREADY]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe54]
set_property port_width 1 [get_debug_ports u_ila_0/probe54]
connect_debug_port u_ila_0/probe54 [get_nets [list design_1_i/processing_system7_0_axi_periph_M00_AXI_WVALID]]
set_property C_CLK_INPUT_FREQ_HZ 300000000 [get_debug_cores dbg_hub]
set_property C_ENABLE_CLK_DIVIDER false [get_debug_cores dbg_hub]
set_property C_USER_SCAN_CHAIN 1 [get_debug_cores dbg_hub]
connect_debug_port dbg_hub/clk [get_nets u_ila_0_FCLK_CLK0]
